import RHFormalization.CanonicalPrimePowerHeatKernelPrimePowerSupport
import RHFormalization.CanonicalPrimePowerHeatKernelGaussianMajorant
import RHFormalization.CanonicalPrimePowerHeatKernelNatValueMajorantSummability

namespace RHFormalization

#check heatKernelGaussianCoreEnvelope_summable
#check heatKernelGaussianCoreEnvelope_eq_abs_weightReal
#check heatKernelGaussianCoreEnvelope_nonneg
#check heatKernelGaussianCoreEnvelope_eq_zero_of_not_isPrimePowerPair
#check heatKernelGaussianCoreEnvelope_eq_valid_primePower_formula
#check heatKernelGaussianCoreEnvelope_le_weight_mul_natValue_inv_cube_of_ge
#check heatKernelNatValueMajorant
#check heatKernelNatValueMajorant_summable
#check Summable.of_nonneg_of_le
#check Summable.congr
#check summable_of_finite_eventually_bounded

#print heatKernelGaussianCoreEnvelope_le_weight_mul_natValue_inv_cube_of_ge
#print heatKernelNatValueMajorant_summable

end RHFormalization
