import RHFormalization.AppendixESharedPackageCompatibility

#check RHFormalization.AppendixESharedPackageCompatibility
#check RHFormalization.buildDMatchesSharedCanonicalPackageFromDetailed
#check RHFormalization.buildHMatchesSharedCanonicalPackageFromCompatibility
#check RHFormalization.buildInterfaceBridgeFromSharedPackageCompatibility
#check RHFormalization.finalRHSpine_after_sharedPackageCompatibility

#print axioms RHFormalization.buildInterfaceBridgeFromSharedPackageCompatibility
#print axioms RHFormalization.finalRHSpine_after_sharedPackageCompatibility
