import RHFormalization.AppendixESharedCanonicalPackage

#check RHFormalization.SharedCanonicalPackageEvidence
#check RHFormalization.buildInterfaceBridgeFromSharedCanonicalPackage
#check RHFormalization.AppendixESharedCanonicalPackageTarget

#print axioms RHFormalization.buildInterfaceBridgeFromSharedCanonicalPackage
