import RHFormalization.AppendixDOperatorPrimePowerDetailedConstruction

#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromPrimePowerLimit
#check RHFormalization.detailedConstructionFromPrimePowerLimit_h_Bcan_matches_shared

#print axioms RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromPrimePowerLimit
#print axioms RHFormalization.detailedConstructionFromPrimePowerLimit_h_Bcan_matches_shared
