import RHFormalization.AppendixDRCutoffEstimateDetailedConstruction

#check RHFormalization.RCutoffEstimateSharedPackage
#check RHFormalization.RCutoffEstimateFiniteCanonicalLimit
#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
#check RHFormalization.detailedConstructionFromRCutoffEstimate_Bcan_matches_tsum

#print axioms RHFormalization.RCutoffEstimateFiniteCanonicalLimit
#print axioms RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
#print axioms RHFormalization.detailedConstructionFromRCutoffEstimate_Bcan_matches_tsum
