import RHFormalization.AppendixESharedPackageFunctionalCompatibility

#check RHFormalization.AppendixESharedPackageFunctionalCompatibility
#check RHFormalization.buildInterfaceBridgeFromSharedPackageFunctionalCompatibility
#check RHFormalization.finalRHSpine_after_sharedPackageFunctionalCompatibility

#print axioms RHFormalization.buildInterfaceBridgeFromSharedPackageFunctionalCompatibility
#print axioms RHFormalization.finalRHSpine_after_sharedPackageFunctionalCompatibility
