import RHFormalization.AppendixDPrimePowerLimitReduction

#check RHFormalization.DOperatorFiniteCanonicalLimitAtOverlapData
#check RHFormalization.buildDOperatorPrimePowerLimitAtOverlapData_fromFiniteCanonicalLimit
#check RHFormalization.buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
#check RHFormalization.finiteCanonicalLimit_h_Bcan_matches_shared

#print axioms RHFormalization.buildDOperatorPrimePowerLimitAtOverlapData_fromFiniteCanonicalLimit
#print axioms RHFormalization.buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
#print axioms RHFormalization.finiteCanonicalLimit_h_Bcan_matches_shared
