import RHFormalization.AppendixDOperatorFiniteCanonicalDetailedConstruction

#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
#check RHFormalization.detailedConstructionFromFiniteCanonicalLimit_Bcan_eq_shared
#check RHFormalization.detailedConstructionFromFiniteCanonicalLimit_h_Bcan_matches_shared

#print axioms RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
#print axioms RHFormalization.detailedConstructionFromFiniteCanonicalLimit_Bcan_eq_shared
#print axioms RHFormalization.detailedConstructionFromFiniteCanonicalLimit_h_Bcan_matches_shared
