import RHFormalization.CanonicalPrimePowerKernelErrorBound

#check RHFormalization.complex_tendsto_zero_of_norm_bound
#check RHFormalization.canonicalPrimePowerStageKernelError
#check RHFormalization.CanonicalPrimePowerKernelErrorBoundData
#check RHFormalization.CanonicalPrimePowerKernelErrorBoundData.toAsymptoticKernelMajorantData
#check RHFormalization.CanonicalPrimePowerKernelErrorBoundData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerKernelErrorBound
#check RHFormalization.canonicalPrimePowerKernelErrorBound_h_Bcan_matches_tsum

#print axioms RHFormalization.complex_tendsto_zero_of_norm_bound
#print axioms RHFormalization.CanonicalPrimePowerKernelErrorBoundData.toAsymptoticKernelMajorantData
#print axioms RHFormalization.CanonicalPrimePowerKernelErrorBoundData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerKernelErrorBound
#print axioms RHFormalization.canonicalPrimePowerKernelErrorBound_h_Bcan_matches_tsum
