import RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeed

#check RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeedData.toExactSpeedMassBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeedData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassExactSpeed
#check RHFormalization.canonicalPrimePowerDWindowExactMassExactSpeed_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeedData.toExactSpeedMassBudgetData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeedData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassExactSpeed
#print axioms RHFormalization.canonicalPrimePowerDWindowExactMassExactSpeed_h_Bcan_matches_tsum
