import RHFormalization.CanonicalPrimePowerDWindowCompactRateBudget

#check RHFormalization.massGrowth_window_tendsto_zero_of_rateBudget
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateBudgetData.toCompactRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateBudgetData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowCompactRateBudget
#check RHFormalization.canonicalPrimePowerDWindowCompactRateBudget_h_Bcan_matches_tsum

#print axioms RHFormalization.massGrowth_window_tendsto_zero_of_rateBudget
#print axioms RHFormalization.CanonicalPrimePowerDWindowCompactRateBudgetData.toCompactRateMassGrowthData
#print axioms RHFormalization.CanonicalPrimePowerDWindowCompactRateBudgetData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowCompactRateBudget
#print axioms RHFormalization.canonicalPrimePowerDWindowCompactRateBudget_h_Bcan_matches_tsum
