import RHFormalization.CanonicalPrimePowerTsumPrincipalPart

#check RHFormalization.canonicalPrimePowerPackageFromKernelTsum_principalPart_at_witness
#check RHFormalization.canonicalPrimePowerPackageFromKernelTsum_oppositePrincipalPart_at_witness
#check RHFormalization.BsharedOppositePrincipalPartData_of_tsum_principalParts

#print axioms RHFormalization.canonicalPrimePowerPackageFromKernelTsum_principalPart_at_witness
#print axioms RHFormalization.canonicalPrimePowerPackageFromKernelTsum_oppositePrincipalPart_at_witness
#print axioms RHFormalization.BsharedOppositePrincipalPartData_of_tsum_principalParts
