import RHFormalization.CanonicalPrimePowerSharpCutoffMassEnvelopeLinearRate

#check RHFormalization.sharpCutoff_explicit_rate_of_massEnvelope_div_L_tendsto_zero
#check RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_massEnvelope_div_L

#print axioms RHFormalization.sharpCutoff_explicit_rate_of_massEnvelope_div_L_tendsto_zero
#print axioms RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_massEnvelope_div_L
