import RHFormalization.CanonicalPrimePowerTsumSeries

#check RHFormalization.CanonicalPrimePowerTsumKernelSeriesData
#check RHFormalization.CanonicalPrimePowerTsumKernelSeriesData.toIndexKernelSeriesData
#check RHFormalization.CanonicalPrimePowerTsumKernelSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerTsumKernelSeries
#check RHFormalization.canonicalPrimePowerTsumKernelSeries_h_Bcan_matches_shared

#print axioms RHFormalization.CanonicalPrimePowerTsumKernelSeriesData.toIndexKernelSeriesData
#print axioms RHFormalization.CanonicalPrimePowerTsumKernelSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerTsumKernelSeries
#print axioms RHFormalization.canonicalPrimePowerTsumKernelSeries_h_Bcan_matches_shared
