import RHFormalization.CanonicalPrimePowerSoundCutoffCounting

#check RHFormalization.PrimePowerSoundCutoffEnumerationData
#check RHFormalization.belowCutoff_subset_countSet_of_sound_center_cutoff
#check RHFormalization.PrimePowerCenterCountingSetData
#check RHFormalization.PrimePowerCenterCountingSetData.toCutoffCountingSetData
#check RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData
#check RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData.toMassCountingSetWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingData.toMassCountingSetWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSoundCounting
#check RHFormalization.canonicalPrimePowerDWindowSoundCounting_h_Bcan_matches_tsum

#print axioms RHFormalization.belowCutoff_subset_countSet_of_sound_center_cutoff
#print axioms RHFormalization.PrimePowerCenterCountingSetData.toCutoffCountingSetData
#print axioms RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData.toMassCountingSetWeightEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSoundCountingData.toMassCountingSetWeightEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSoundCountingData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSoundCounting
#print axioms RHFormalization.canonicalPrimePowerDWindowSoundCounting_h_Bcan_matches_tsum
