import RHFormalization.CanonicalPrimePowerSharpCutoffSharedLimitMajorant

#check RHFormalization.windowLimit_norm_le_majorant_of_sharedKernel_norm_le
#check RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData
#check RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toChosenLengthMassEnvelopeData
#check RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthSharedMajorant
#check RHFormalization.canonicalPrimePowerSharpCutoffChosenLengthSharedMajorant_h_Bcan_matches_tsum

#print axioms RHFormalization.windowLimit_norm_le_majorant_of_sharedKernel_norm_le
#print axioms RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toChosenLengthMassEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthSharedMajorant
#print axioms RHFormalization.canonicalPrimePowerSharpCutoffChosenLengthSharedMajorant_h_Bcan_matches_tsum
