import RHFormalization.CanonicalPrimePowerSharedKernelMajorant

#check RHFormalization.weighted_shared_kernel_norm_le_weight_norm_mul_majorant
#check RHFormalization.CanonicalPrimePowerSharedKernelMajorantData
#check RHFormalization.CanonicalPrimePowerSharedKernelMajorantData.toUniformWindowErrorData
#check RHFormalization.CanonicalPrimePowerSharedKernelMajorantData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharedKernelMajorant
#check RHFormalization.canonicalPrimePowerSharedKernelMajorant_h_Bcan_matches_tsum

#print axioms RHFormalization.weighted_shared_kernel_norm_le_weight_norm_mul_majorant
#print axioms RHFormalization.CanonicalPrimePowerSharedKernelMajorantData.toUniformWindowErrorData
#print axioms RHFormalization.CanonicalPrimePowerSharedKernelMajorantData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharedKernelMajorant
#print axioms RHFormalization.canonicalPrimePowerSharedKernelMajorant_h_Bcan_matches_tsum
