import RHFormalization.CanonicalPrimePowerProductWindowError

#check RHFormalization.actual_kernel_error_sum_tendsto_zero_of_weightC_window_product
#check RHFormalization.CanonicalPrimePowerProductWindowErrorData
#check RHFormalization.CanonicalPrimePowerProductWindowErrorData.toActualKernelErrorData
#check RHFormalization.CanonicalPrimePowerProductWindowErrorData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerProductWindowError
#check RHFormalization.canonicalPrimePowerProductWindowError_h_Bcan_matches_tsum

#print axioms RHFormalization.actual_kernel_error_sum_tendsto_zero_of_weightC_window_product
#print axioms RHFormalization.CanonicalPrimePowerProductWindowErrorData.toActualKernelErrorData
#print axioms RHFormalization.CanonicalPrimePowerProductWindowErrorData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerProductWindowError
#print axioms RHFormalization.canonicalPrimePowerProductWindowError_h_Bcan_matches_tsum
