import RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudget

#check RHFormalization.massGrowth_window_le_separated_budget
#check RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudgetData.toCompactRateBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudgetData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSeparatedRateBudget
#check RHFormalization.canonicalPrimePowerDWindowSeparatedRateBudget_h_Bcan_matches_tsum

#print axioms RHFormalization.massGrowth_window_le_separated_budget
#print axioms RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudgetData.toCompactRateBudgetData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSeparatedRateBudgetData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSeparatedRateBudget
#print axioms RHFormalization.canonicalPrimePowerDWindowSeparatedRateBudget_h_Bcan_matches_tsum
