import RHFormalization.CanonicalPrimePowerWeightEnvelope

#check RHFormalization.PrimePowerPair.norm_weightC_eq_abs_weightReal
#check RHFormalization.PrimePowerPair.norm_weightC_le_of_abs_weightReal_le
#check RHFormalization.PrimePowerWeightEnvelopeData
#check RHFormalization.PrimePowerWeightEnvelopeData.norm_weightC_le
#check RHFormalization.PrimePowerMassCountingWeightEnvelopeData
#check RHFormalization.PrimePowerMassCountingWeightEnvelopeData.toMassCountingEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingWeightEnvelopeData.toMassCountingSpeedComparisonData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingWeightEnvelopeData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCountingWeightEnvelope
#check RHFormalization.canonicalPrimePowerDWindowMassCountingWeightEnvelope_h_Bcan_matches_tsum

#print axioms RHFormalization.PrimePowerPair.norm_weightC_eq_abs_weightReal
#print axioms RHFormalization.PrimePowerPair.norm_weightC_le_of_abs_weightReal_le
#print axioms RHFormalization.PrimePowerWeightEnvelopeData.norm_weightC_le
#print axioms RHFormalization.PrimePowerMassCountingWeightEnvelopeData.toMassCountingEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingWeightEnvelopeData.toMassCountingSpeedComparisonData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingWeightEnvelopeData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCountingWeightEnvelope
#print axioms RHFormalization.canonicalPrimePowerDWindowMassCountingWeightEnvelope_h_Bcan_matches_tsum
