import RHFormalization.CanonicalPrimePowerMassGrowthWindow

#check RHFormalization.weightC_window_product_tendsto_zero_of_massGrowth
#check RHFormalization.CanonicalPrimePowerMassGrowthWindowData
#check RHFormalization.CanonicalPrimePowerMassGrowthWindowData.toProductWindowErrorData
#check RHFormalization.CanonicalPrimePowerMassGrowthWindowData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerMassGrowthWindow
#check RHFormalization.canonicalPrimePowerMassGrowthWindow_h_Bcan_matches_tsum

#print axioms RHFormalization.weightC_window_product_tendsto_zero_of_massGrowth
#print axioms RHFormalization.CanonicalPrimePowerMassGrowthWindowData.toProductWindowErrorData
#print axioms RHFormalization.CanonicalPrimePowerMassGrowthWindowData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerMassGrowthWindow
#print axioms RHFormalization.canonicalPrimePowerMassGrowthWindow_h_Bcan_matches_tsum
