import RHFormalization.CanonicalPrimePowerMassUpperEnvelope

#check RHFormalization.PrimePowerMassEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeData.toExactWindowSpeedEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassEnvelope
#check RHFormalization.canonicalPrimePowerDWindowMassEnvelope_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeData.toExactWindowSpeedEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassEnvelope
#print axioms RHFormalization.canonicalPrimePowerDWindowMassEnvelope_h_Bcan_matches_tsum
