import RHFormalization.CanonicalPrimePowerSharpCutoffMassEnvelopeExplicitRate

#check RHFormalization.sharpCutoffConcreteChosen_speed_coordSet_eq
#check RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_explicit_rate

#print axioms RHFormalization.sharpCutoffConcreteChosen_speed_coordSet_eq
#print axioms RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_explicit_rate
