import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification

#check RHFormalization.PrimePowerDWindowKernelIdentificationData
#check RHFormalization.CanonicalPrimePowerDWindowIdentifiedRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowIdentifiedRateMassGrowthData.toDWindowRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowIdentifiedRateMassGrowthData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowIdentifiedRateMassGrowth
#check RHFormalization.canonicalPrimePowerDWindowIdentifiedRateMassGrowth_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowIdentifiedRateMassGrowthData.toDWindowRateMassGrowthData
#print axioms RHFormalization.CanonicalPrimePowerDWindowIdentifiedRateMassGrowthData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowIdentifiedRateMassGrowth
#print axioms RHFormalization.canonicalPrimePowerDWindowIdentifiedRateMassGrowth_h_Bcan_matches_tsum
