import RHFormalization.CanonicalPrimePowerCutoffMassBound

#check RHFormalization.PrimePowerWeightMassBoundData
#check RHFormalization.CanonicalPrimePowerRCutoffMassBoundWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassBoundWindowData.toRCutoffGrowthMassWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassBoundWindowData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffMassBound
#check RHFormalization.canonicalPrimePowerRCutoffMassBound_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassBoundWindowData.toRCutoffGrowthMassWindowData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassBoundWindowData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffMassBound
#print axioms RHFormalization.canonicalPrimePowerRCutoffMassBound_h_Bcan_matches_tsum
