import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds

#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.toSoundCountingData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSoundCountingFactorBounds
#check RHFormalization.canonicalPrimePowerDWindowSoundCountingFactorBounds_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.toSoundCountingData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSoundCountingFactorBounds
#print axioms RHFormalization.canonicalPrimePowerDWindowSoundCountingFactorBounds_h_Bcan_matches_tsum
