import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLength

#check RHFormalization.mass_div_chosenLength_le_inv
#check RHFormalization.sharpCutoff_massEnvelope_div_chosenLength_tendsto_zero
#check RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_chosenLength

#print axioms RHFormalization.mass_div_chosenLength_le_inv
#print axioms RHFormalization.sharpCutoff_massEnvelope_div_chosenLength_tendsto_zero
#print axioms RHFormalization.sharpCutoffMassEnvelope_div_windowSpeed_tendsto_zero_of_chosenLength
