import RHFormalization.CanonicalPrimePowerUniformWindowError

#check RHFormalization.weighted_kernel_error_norm_le_weight_norm_mul
#check RHFormalization.canonicalPrimePowerActualTermError_le_weight_norm_mul_window
#check RHFormalization.CanonicalPrimePowerUniformWindowErrorData
#check RHFormalization.CanonicalPrimePowerUniformWindowErrorData.toWindowMassErrorData
#check RHFormalization.CanonicalPrimePowerUniformWindowErrorData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerUniformWindowError
#check RHFormalization.canonicalPrimePowerUniformWindowError_h_Bcan_matches_tsum

#print axioms RHFormalization.weighted_kernel_error_norm_le_weight_norm_mul
#print axioms RHFormalization.canonicalPrimePowerActualTermError_le_weight_norm_mul_window
#print axioms RHFormalization.CanonicalPrimePowerUniformWindowErrorData.toWindowMassErrorData
#print axioms RHFormalization.CanonicalPrimePowerUniformWindowErrorData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerUniformWindowError
#print axioms RHFormalization.canonicalPrimePowerUniformWindowError_h_Bcan_matches_tsum
