import RHFormalization.CanonicalPrimePowerSeries

#check RHFormalization.finite_sum_tendsto_of_hasSum_finset_exhaustion
#check RHFormalization.CanonicalPrimePowerSeriesData
#check RHFormalization.CanonicalPrimePowerSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSeries
#check RHFormalization.canonicalPrimePowerSeries_h_Bcan_matches_shared

#print axioms RHFormalization.finite_sum_tendsto_of_hasSum_finset_exhaustion
#print axioms RHFormalization.CanonicalPrimePowerSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSeries
#print axioms RHFormalization.canonicalPrimePowerSeries_h_Bcan_matches_shared
