import RHFormalization.CanonicalPrimePowerIndexExhaustion

#check RHFormalization.finset_tendsto_atTop_of_eventually_mem
#check RHFormalization.CanonicalPrimePowerIndexKernelSeriesData
#check RHFormalization.CanonicalPrimePowerIndexKernelSeriesData.toKernelSeriesData
#check RHFormalization.CanonicalPrimePowerIndexKernelSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerIndexKernelSeries
#check RHFormalization.canonicalPrimePowerIndexKernelSeries_h_Bcan_matches_shared

#print axioms RHFormalization.finset_tendsto_atTop_of_eventually_mem
#print axioms RHFormalization.CanonicalPrimePowerIndexKernelSeriesData.toKernelSeriesData
#print axioms RHFormalization.CanonicalPrimePowerIndexKernelSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerIndexKernelSeries
#print axioms RHFormalization.canonicalPrimePowerIndexKernelSeries_h_Bcan_matches_shared
