import RHFormalization.CanonicalPrimePowerCountingSetEnvelope

#check RHFormalization.PrimePowerCutoffCountingSetData
#check RHFormalization.PrimePowerCutoffCountingSetData.card_belowCutoff_le_countEnvelope
#check RHFormalization.PrimePowerMassCountingSetWeightEnvelopeData
#check RHFormalization.PrimePowerMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCountingSetWeightEnvelope
#check RHFormalization.canonicalPrimePowerDWindowMassCountingSetWeightEnvelope_h_Bcan_matches_tsum

#print axioms RHFormalization.PrimePowerCutoffCountingSetData.card_belowCutoff_le_countEnvelope
#print axioms RHFormalization.PrimePowerMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCountingSetWeightEnvelope
#print axioms RHFormalization.canonicalPrimePowerDWindowMassCountingSetWeightEnvelope_h_Bcan_matches_tsum
