import RHFormalization.CanonicalPrimePowerHeatKernelPrimePowerSupport

#check RHFormalization.heatKernelGaussianCoreEnvelope_eq_zero_of_not_isPrimePowerPair
#check RHFormalization.heatKernelGaussianCoreEnvelope_eq_valid_primePower_formula

#print axioms RHFormalization.heatKernelGaussianCoreEnvelope_eq_zero_of_not_isPrimePowerPair
#print axioms RHFormalization.heatKernelGaussianCoreEnvelope_eq_valid_primePower_formula
