import RHFormalization.CanonicalPrimePowerDWindowRateMassGrowth

#check RHFormalization.CanonicalPrimePowerDWindowRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowRateMassGrowthData.toRCutoffRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowRateMassGrowthData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowRateMassGrowth
#check RHFormalization.canonicalPrimePowerDWindowRateMassGrowth_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowRateMassGrowthData.toRCutoffRateMassGrowthData
#print axioms RHFormalization.CanonicalPrimePowerDWindowRateMassGrowthData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowRateMassGrowth
#print axioms RHFormalization.canonicalPrimePowerDWindowRateMassGrowth_h_Bcan_matches_tsum
