import RHFormalization.CanonicalPrimePowerWeightedSummabilityEnvelope

#check RHFormalization.weightedKernelMajorant_summable_of_envelope
#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedEnvelopeData.toExactWindowSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedEnvelopeData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactWindowSpeedEnvelope
#check RHFormalization.canonicalPrimePowerDWindowExactWindowSpeedEnvelope_h_Bcan_matches_tsum

#print axioms RHFormalization.weightedKernelMajorant_summable_of_envelope
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedEnvelopeData.toExactWindowSpeedData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedEnvelopeData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactWindowSpeedEnvelope
#print axioms RHFormalization.canonicalPrimePowerDWindowExactWindowSpeedEnvelope_h_Bcan_matches_tsum
