import RHFormalization.CanonicalPrimePowerWindowMassError

#check RHFormalization.real_tendsto_zero_of_nonneg_bound
#check RHFormalization.actual_kernel_error_sum_tendsto_zero_of_window_mass_bound
#check RHFormalization.CanonicalPrimePowerWindowMassErrorData
#check RHFormalization.CanonicalPrimePowerWindowMassErrorData.toActualKernelErrorData
#check RHFormalization.CanonicalPrimePowerWindowMassErrorData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerWindowMassError
#check RHFormalization.canonicalPrimePowerWindowMassError_h_Bcan_matches_tsum

#print axioms RHFormalization.real_tendsto_zero_of_nonneg_bound
#print axioms RHFormalization.actual_kernel_error_sum_tendsto_zero_of_window_mass_bound
#print axioms RHFormalization.CanonicalPrimePowerWindowMassErrorData.toActualKernelErrorData
#print axioms RHFormalization.CanonicalPrimePowerWindowMassErrorData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerWindowMassError
#print axioms RHFormalization.canonicalPrimePowerWindowMassError_h_Bcan_matches_tsum
