import RHFormalization.CanonicalPrimePowerDWindowSpeedAPI

#check RHFormalization.DCanonicalWindowCompactSpeedAPI
#check RHFormalization.buildPrimePowerDWindowCompactSpeedRateDataFromWindowSpeedAPI
#check RHFormalization.CanonicalPrimePowerDWindowSpeedAPILimitMajorantMassSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowSpeedAPILimitMajorantMassSpeedData.toLimitMajorantMassSpeedEstimateData
#check RHFormalization.CanonicalPrimePowerDWindowSpeedAPILimitMajorantMassSpeedData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSpeedAPI
#check RHFormalization.canonicalPrimePowerDWindowSpeedAPI_h_Bcan_matches_tsum

#print axioms RHFormalization.buildPrimePowerDWindowCompactSpeedRateDataFromWindowSpeedAPI
#print axioms RHFormalization.CanonicalPrimePowerDWindowSpeedAPILimitMajorantMassSpeedData.toLimitMajorantMassSpeedEstimateData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSpeedAPILimitMajorantMassSpeedData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSpeedAPI
#print axioms RHFormalization.canonicalPrimePowerDWindowSpeedAPI_h_Bcan_matches_tsum
