import RHFormalization.CanonicalPrimePowerConcreteTsumPackage

#check RHFormalization.canonicalPrimePowerPackageFromKernelTsum
#check RHFormalization.CanonicalPrimePowerConcreteTsumKernelSeriesData
#check RHFormalization.CanonicalPrimePowerConcreteTsumKernelSeriesData.toTsumKernelSeriesData
#check RHFormalization.CanonicalPrimePowerConcreteTsumKernelSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerConcreteTsumKernelSeries
#check RHFormalization.canonicalPrimePowerConcreteTsumKernelSeries_h_Bcan_matches_tsum

#print axioms RHFormalization.canonicalPrimePowerPackageFromKernelTsum
#print axioms RHFormalization.CanonicalPrimePowerConcreteTsumKernelSeriesData.toTsumKernelSeriesData
#print axioms RHFormalization.CanonicalPrimePowerConcreteTsumKernelSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerConcreteTsumKernelSeries
#print axioms RHFormalization.canonicalPrimePowerConcreteTsumKernelSeries_h_Bcan_matches_tsum
