import RHFormalization.CanonicalPrimePowerRCutoffRatePackaged

#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData
#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toRCutoffEnumeratedMassWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffRatePackaged
#check RHFormalization.canonicalPrimePowerRCutoffRatePackaged_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toRCutoffEnumeratedMassWindowData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffRatePackaged
#print axioms RHFormalization.canonicalPrimePowerRCutoffRatePackaged_h_Bcan_matches_tsum
