import RHFormalization.CanonicalPrimePowerSummabilityMajorant

#check RHFormalization.CanonicalPrimePowerMajorantKernelSeriesData
#check RHFormalization.CanonicalPrimePowerMajorantKernelSeriesData.toConcreteTsumKernelSeriesData
#check RHFormalization.CanonicalPrimePowerMajorantKernelSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerMajorantKernelSeries
#check RHFormalization.canonicalPrimePowerMajorantKernelSeries_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerMajorantKernelSeriesData.toConcreteTsumKernelSeriesData
#print axioms RHFormalization.CanonicalPrimePowerMajorantKernelSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerMajorantKernelSeries
#print axioms RHFormalization.canonicalPrimePowerMajorantKernelSeries_h_Bcan_matches_tsum
