import RHFormalization.CanonicalPrimePowerKernelSeries

#check RHFormalization.CanonicalPrimePowerKernelSeriesData
#check RHFormalization.CanonicalPrimePowerKernelSeriesData.toSeriesData
#check RHFormalization.CanonicalPrimePowerKernelSeriesData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerKernelSeries
#check RHFormalization.canonicalPrimePowerKernelSeries_h_Bcan_matches_shared

#print axioms RHFormalization.CanonicalPrimePowerKernelSeriesData.toSeriesData
#print axioms RHFormalization.CanonicalPrimePowerKernelSeriesData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerKernelSeries
#print axioms RHFormalization.canonicalPrimePowerKernelSeries_h_Bcan_matches_shared
