import RHFormalization.CanonicalPrimePowerHeatKernelGaussianMajorant

#check RHFormalization.exists_natValue_threshold_exp_neg_center_sq_le_inv_cube
#check RHFormalization.heatKernelGaussianCoreEnvelope_le_weight_mul_natValue_inv_cube_of_ge

#print axioms RHFormalization.exists_natValue_threshold_exp_neg_center_sq_le_inv_cube
#print axioms RHFormalization.heatKernelGaussianCoreEnvelope_le_weight_mul_natValue_inv_cube_of_ge
