import RHFormalization.CanonicalPrimePowerHeatKernelNatValueMajorantSummability

#check RHFormalization.heatKernelNatValueMajorant_eq_zero_of_not_isPrimePowerPair
#check RHFormalization.heatKernelNatValueMajorant_eq_valid_primePower_formula
#check RHFormalization.heatKernelNatValueMajorant_summable_of_model
#check RHFormalization.heatKernelNatValueMajorant_summable

#print axioms RHFormalization.heatKernelNatValueMajorant_eq_zero_of_not_isPrimePowerPair
#print axioms RHFormalization.heatKernelNatValueMajorant_eq_valid_primePower_formula
#print axioms RHFormalization.heatKernelNatValueMajorant_summable_of_model
