import RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeed

#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedData.toSpeedAPILimitMajorantMassSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactWindowSpeed
#check RHFormalization.canonicalPrimePowerDWindowExactWindowSpeed_h_Bcan_matches_tsum

#print axioms RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedData.toSpeedAPILimitMajorantMassSpeedData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeedData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactWindowSpeed
#print axioms RHFormalization.canonicalPrimePowerDWindowExactWindowSpeed_h_Bcan_matches_tsum
