import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget

#check RHFormalization.heatKernelG
#check RHFormalization.heatKernelWeightedEnvelope
#check RHFormalization.heatKernelWeightedEnvelope_apply
#check RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#check RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#check RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffHeatKernelWeighted
#check RHFormalization.canonicalPrimePowerSharpCutoffHeatKernelWeighted_h_Bcan_matches_tsum

#print axioms RHFormalization.heatKernelG
#print axioms RHFormalization.heatKernelWeightedEnvelope
#print axioms RHFormalization.heatKernelWeightedEnvelope_apply
#print axioms RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffHeatKernelWeighted
#print axioms RHFormalization.canonicalPrimePowerSharpCutoffHeatKernelWeighted_h_Bcan_matches_tsum
