import RHFormalization.CanonicalPrimePowerDWindowSpeedBudget

#check RHFormalization.massWindowBudget_tendsto_zero_of_speed
#check RHFormalization.CanonicalPrimePowerDWindowSpeedBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowSpeedBudgetData.toSeparatedRateBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowSpeedBudgetData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSpeedBudget
#check RHFormalization.canonicalPrimePowerDWindowSpeedBudget_h_Bcan_matches_tsum

#print axioms RHFormalization.massWindowBudget_tendsto_zero_of_speed
#print axioms RHFormalization.CanonicalPrimePowerDWindowSpeedBudgetData.toSeparatedRateBudgetData
#print axioms RHFormalization.CanonicalPrimePowerDWindowSpeedBudgetData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowSpeedBudget
#print axioms RHFormalization.canonicalPrimePowerDWindowSpeedBudget_h_Bcan_matches_tsum
