import RHFormalization.CanonicalPrimePowerCountWeightQuotient

#check RHFormalization.countWeight_div_denominator_tendsto_zero_of_numerator_bound
#check RHFormalization.countWeight_div_denominator_tendsto_zero_of_cutoff_numerator_bound

#print axioms RHFormalization.countWeight_div_denominator_tendsto_zero_of_numerator_bound
#print axioms RHFormalization.countWeight_div_denominator_tendsto_zero_of_cutoff_numerator_bound
