import RHFormalization.CanonicalPrimePowerAsymptoticKernel

#check RHFormalization.finiteCanonical_tendsto_tsum_of_kernel_error_tendsto_zero
#check RHFormalization.CanonicalPrimePowerAsymptoticKernelMajorantData
#check RHFormalization.CanonicalPrimePowerAsymptoticKernelMajorantData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerAsymptoticKernel
#check RHFormalization.canonicalPrimePowerAsymptoticKernel_h_Bcan_matches_tsum

#print axioms RHFormalization.finiteCanonical_tendsto_tsum_of_kernel_error_tendsto_zero
#print axioms RHFormalization.CanonicalPrimePowerAsymptoticKernelMajorantData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerAsymptoticKernel
#print axioms RHFormalization.canonicalPrimePowerAsymptoticKernel_h_Bcan_matches_tsum
