import RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudget

#check RHFormalization.enumeratedPrimePowerMass
#check RHFormalization.enumeratedPrimePowerMass_nonneg
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudgetData.toSpeedBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudgetData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassSpeedBudget
#check RHFormalization.canonicalPrimePowerDWindowExactMassSpeedBudget_h_Bcan_matches_tsum

#print axioms RHFormalization.enumeratedPrimePowerMass_nonneg
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudgetData.toSpeedBudgetData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudgetData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassSpeedBudget
#print axioms RHFormalization.canonicalPrimePowerDWindowExactMassSpeedBudget_h_Bcan_matches_tsum
