import RHFormalization.CanonicalPrimePowerCountWeightProductBound

#check RHFormalization.countWeight_product_le_of_factor_bounds
#check RHFormalization.countWeight_div_denominator_tendsto_zero_of_factor_bounds
#check RHFormalization.countWeight_div_denominator_tendsto_zero_of_cutoff_factor_bounds

#print axioms RHFormalization.countWeight_product_le_of_factor_bounds
#print axioms RHFormalization.countWeight_div_denominator_tendsto_zero_of_factor_bounds
#print axioms RHFormalization.countWeight_div_denominator_tendsto_zero_of_cutoff_factor_bounds
