import RHFormalization.CanonicalPrimePowerMassEnvelopeSpeedComparison

#check RHFormalization.massEnvelope_div_windowSpeed_tendsto_zero_of_comparison
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData.toMassEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassEnvelopeSpeedComparison
#check RHFormalization.canonicalPrimePowerDWindowMassEnvelopeSpeedComparison_h_Bcan_matches_tsum

#print axioms RHFormalization.massEnvelope_div_windowSpeed_tendsto_zero_of_comparison
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData.toMassEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassEnvelopeSpeedComparison
#print axioms RHFormalization.canonicalPrimePowerDWindowMassEnvelopeSpeedComparison_h_Bcan_matches_tsum
