import RHFormalization.CanonicalPrimePowerExhaustion

#check RHFormalization.CanonicalPrimePowerExhaustionData
#check RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerExhaustion
#check RHFormalization.canonicalPrimePowerExhaustion_h_Bcan_matches_shared

#print axioms RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerExhaustion
#print axioms RHFormalization.canonicalPrimePowerExhaustion_h_Bcan_matches_shared
