import RHFormalization.CanonicalPrimePowerDWindowKernelEstimate

#check RHFormalization.primePower_kernel_window_error_eventually_of_DCanonicalWindow
#check RHFormalization.PrimePowerKernelWindowCompactBridgeData
#check RHFormalization.PrimePowerKernelWindowCompactBridgeData.eventual_kernel_window_error

#print axioms RHFormalization.primePower_kernel_window_error_eventually_of_DCanonicalWindow
#print axioms RHFormalization.PrimePowerKernelWindowCompactBridgeData.eventual_kernel_window_error
