import RHFormalization.CanonicalPrimePowerDWindowExactSpeed

#check RHFormalization.PrimePowerDWindowCompactSpeedRateData
#check RHFormalization.PrimePowerDWindowCompactSpeedRateData.toCompactRateData
#check RHFormalization.CanonicalPrimePowerDWindowExactSpeedMassBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowExactSpeedMassBudgetData.toExactMassSpeedBudgetData
#check RHFormalization.CanonicalPrimePowerDWindowExactSpeedMassBudgetData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactSpeed
#check RHFormalization.canonicalPrimePowerDWindowExactSpeed_h_Bcan_matches_tsum

#print axioms RHFormalization.PrimePowerDWindowCompactSpeedRateData.toCompactRateData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactSpeedMassBudgetData.toExactMassSpeedBudgetData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactSpeedMassBudgetData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactSpeed
#print axioms RHFormalization.canonicalPrimePowerDWindowExactSpeed_h_Bcan_matches_tsum
