import RHFormalization.CanonicalPrimePowerDWindowLimitMajorant

#check RHFormalization.sharedKernel_norm_le_majorant_of_window_limit
#check RHFormalization.CanonicalPrimePowerDWindowLimitMajorantMassSpeedEstimateData
#check RHFormalization.CanonicalPrimePowerDWindowLimitMajorantMassSpeedEstimateData.toExactMassSpeedEstimateData
#check RHFormalization.CanonicalPrimePowerDWindowLimitMajorantMassSpeedEstimateData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowLimitMajorant
#check RHFormalization.canonicalPrimePowerDWindowLimitMajorant_h_Bcan_matches_tsum

#print axioms RHFormalization.sharedKernel_norm_le_majorant_of_window_limit
#print axioms RHFormalization.CanonicalPrimePowerDWindowLimitMajorantMassSpeedEstimateData.toExactMassSpeedEstimateData
#print axioms RHFormalization.CanonicalPrimePowerDWindowLimitMajorantMassSpeedEstimateData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowLimitMajorant
#print axioms RHFormalization.canonicalPrimePowerDWindowLimitMajorant_h_Bcan_matches_tsum
