import RHFormalization.CanonicalPrimePowerRCutoffExhaustion

#check RHFormalization.primePower_indices_eventually_contains_of_R_cutoff
#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toMassGrowthWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffMassGrowthWindow
#check RHFormalization.canonicalPrimePowerRCutoffMassGrowthWindow_h_Bcan_matches_tsum

#print axioms RHFormalization.primePower_indices_eventually_contains_of_R_cutoff
#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toMassGrowthWindowData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerRCutoffMassGrowthWindow
#print axioms RHFormalization.canonicalPrimePowerRCutoffMassGrowthWindow_h_Bcan_matches_tsum
