import RHFormalization.CanonicalPrimePowerDWindowCompactRate

#check RHFormalization.PrimePowerDWindowCompactRateData
#check RHFormalization.PrimePowerDWindowCompactRateData.active_window_rate
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateMassGrowthData.toIdentifiedRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerDWindowCompactRateMassGrowthData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowCompactRateMassGrowth
#check RHFormalization.canonicalPrimePowerDWindowCompactRateMassGrowth_h_Bcan_matches_tsum

#print axioms RHFormalization.PrimePowerDWindowCompactRateData.active_window_rate
#print axioms RHFormalization.CanonicalPrimePowerDWindowCompactRateMassGrowthData.toIdentifiedRateMassGrowthData
#print axioms RHFormalization.CanonicalPrimePowerDWindowCompactRateMassGrowthData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowCompactRateMassGrowth
#print axioms RHFormalization.canonicalPrimePowerDWindowCompactRateMassGrowth_h_Bcan_matches_tsum
