import RHFormalization.CanonicalPrimePowerMassCountingEnvelope

#check RHFormalization.enumeratedPrimePowerMass_le_card_mul_weightBound
#check RHFormalization.enumeratedPrimePowerMass_le_countEnvelope_mul_weightEnvelope
#check RHFormalization.PrimePowerMassCountingEnvelopeData
#check RHFormalization.PrimePowerMassCountingEnvelopeData.toMassEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSpeedComparisonData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSpeedComparisonData.toMassEnvelopeSpeedComparisonData
#check RHFormalization.CanonicalPrimePowerDWindowMassCountingSpeedComparisonData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCounting
#check RHFormalization.canonicalPrimePowerDWindowMassCounting_h_Bcan_matches_tsum

#print axioms RHFormalization.enumeratedPrimePowerMass_le_card_mul_weightBound
#print axioms RHFormalization.enumeratedPrimePowerMass_le_countEnvelope_mul_weightEnvelope
#print axioms RHFormalization.PrimePowerMassCountingEnvelopeData.toMassEnvelopeData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingSpeedComparisonData.toMassEnvelopeSpeedComparisonData
#print axioms RHFormalization.CanonicalPrimePowerDWindowMassCountingSpeedComparisonData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCounting
#print axioms RHFormalization.canonicalPrimePowerDWindowMassCounting_h_Bcan_matches_tsum
