import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromExactWeightedEnvelope

namespace RHFormalization

#check buildChosenLengthDLimitPayloadFromExactWeightedEnvelope
#check buildDDetailedConstructionWithOperatorLegalityFromExactWeightedEnvelopePayload

#print axioms buildChosenLengthDLimitPayloadFromExactWeightedEnvelope
#print axioms buildDDetailedConstructionWithOperatorLegalityFromExactWeightedEnvelopePayload

end RHFormalization
