import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffSharedLimitMajorant
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope

namespace RHFormalization

#check ChosenLengthDLimitPayload
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDLimitPayload

#check CanonicalPrimePowerSharpCutoffSharedMajorantData
#print CanonicalPrimePowerSharpCutoffSharedMajorantData

#check CanonicalPrimePowerSharpCutoffSharedMajorantData.toChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffSharedMajorantData.toChosenLengthMassEnvelopeData

#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData

end RHFormalization
