import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSelectedYFromLimits

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthLimits
#print axioms buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthLimits

end RHFormalization
