import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSelectedYFromWindowFR

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthWindowFR
#print axioms buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthWindowFR

end RHFormalization
