import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromDisplacementKernel
import RHFormalization.CanonicalPrimePowerSharpCutoffExactWeightedEnvelope

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffExactWeightedEnvelopeData
#print CanonicalPrimePowerSharpCutoffExactWeightedEnvelopeData

#check CanonicalPrimePowerSharpCutoffExactWeightedEnvelopeData.toDisplacementKernelData
#print CanonicalPrimePowerSharpCutoffExactWeightedEnvelopeData.toDisplacementKernelData

end RHFormalization
