import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthAlignedDetailedConstruction

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthAligned
#print axioms buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthAligned

end RHFormalization
