import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromExactWeightedEnvelope
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData

#check buildChosenLengthDLimitPayloadFromExactWeightedEnvelope
#check buildDDetailedConstructionWithOperatorLegalityFromExactWeightedEnvelopePayload

end RHFormalization
