import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffSharedLimitMajorant
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope

namespace RHFormalization

#check ChosenLengthDLimitPayload
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDLimitPayload

#check CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData
#print CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData

#check CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData.toChosenLengthMassEnvelopeData

#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData

end RHFormalization
