import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget

namespace RHFormalization

#check buildChosenLengthDLimitPayloadFromHeatKernelWeighted
#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData

end RHFormalization
