import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSelectedYFromFR

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthFR
#print axioms buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthFR

end RHFormalization
