import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromDisplacementKernel

namespace RHFormalization

#check buildChosenLengthDLimitPayloadFromDisplacementKernel
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDisplacementKernelPayload

#print axioms buildChosenLengthDLimitPayloadFromDisplacementKernel
#print axioms buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDisplacementKernelPayload

end RHFormalization
