import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted

namespace RHFormalization

#check buildChosenLengthDLimitPayloadFromHeatKernelWeighted
#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#print axioms buildChosenLengthDLimitPayloadFromHeatKernelWeighted
#print axioms buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

end RHFormalization
