import RHFormalization.DOverlapFromStageSplitLimits
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDetailedConstruction
import RHFormalization.AppendixDPrimePowerLimitReduction
import RHFormalization.DFHLimitConcrete
import RHFormalization.DMasterResidualConcrete

namespace RHFormalization

#check DOverlapIdentityAPI_from_pointwise_stage_limits

#check DFHLimitData.compact_uniform_F_stage_convergence
#check DMasterResidualData.compact_uniform_residual_convergence

#check buildDOperatorPrimePowerLimitAtOverlapData_fromFiniteCanonicalLimit
#check buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
#check DOperatorPrimePowerLimitAtOverlapData
#print DOperatorPrimePowerLimitAtOverlapData

#check SharpCutoffChosenLengthFiniteCanonicalLimit
#print SharpCutoffChosenLengthFiniteCanonicalLimit

#check SharpCutoffChosenLengthSharedPackage
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData

#check DFiniteStagePackageFromOperatorLayer.toStageSplit
#check DFiniteStageSplitAPI.h_stage_split

-- search likely right-half-plane-to-Omega helper names
#check RightHalfPlane
#print RightHalfPlane
#check Omega

end RHFormalization
