import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromSharedMajorant
import RHFormalization.CanonicalPrimePowerSharpCutoffDisplacementKernel

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData
#print CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData

#check CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData.toSharedMajorantData
#print CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData.toSharedMajorantData

end RHFormalization
