import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromSharedMajorant

namespace RHFormalization

#check buildChosenLengthDLimitPayloadFromSharedMajorant
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthSharedMajorantPayload

#print axioms buildChosenLengthDLimitPayloadFromSharedMajorant
#print axioms buildDDetailedConstructionWithOperatorLegalityFromChosenLengthSharedMajorantPayload

end RHFormalization
