import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromExactWeightedEnvelope
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget

namespace RHFormalization

#check CanonicalPrimePowerHeatKernelWeightedSummabilityTargetData
#print CanonicalPrimePowerHeatKernelWeightedSummabilityTargetData

-- likely names; some may fail
#check CanonicalPrimePowerHeatKernelWeightedSummabilityTargetData.toExactWeightedEnvelopeData
#check CanonicalPrimePowerHeatKernelWeightedSummabilityTargetData.toSharpCutoffExactWeightedEnvelopeData

end RHFormalization
