import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerCutoffMassEnumeration
import RHFormalization.CanonicalPrimePowerMassEnvelope
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

#check DFiniteStagePackageFromOperatorLayer
#check heatKernelG

#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#print DCanonicalWindowSharpCutoffConcreteChosenSpeedData

#check PrimePowerDWindowKernelIdentificationData
#print PrimePowerDWindowKernelIdentificationData

#check PrimePowerWeightCutoffEnumerationData
#print PrimePowerWeightCutoffEnumerationData

#check PrimePowerMassEnvelopeData
#print PrimePowerMassEnvelopeData

#check sharpCutoffDCanonicalWindowData
#check displacementCanonicalKernel

end RHFormalization
