import RHFormalization.CanonicalPrimePowerSharpCutoffClosedDWindowSource
import RHFormalization.SelectedFiniteOperatorLayer
import RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimate
import RHFormalization.FinalRHFromDWindowExactMassExactSpeed
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope

namespace RHFormalization

noncomputable section

#check selectedFiniteOperatorLayer

#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData
#print CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.mk

#check SelectedSharpCutoffClosedDWindowSource
#print SelectedSharpCutoffClosedDWindowSource

-- These may or may not exist. Unknown identifiers are useful signal here.
#check selectedSharpCutoffClosedDWindowSource
#check selectedDWindowMassCountingSetWeightEnvelopeData
#check selectedMassCountingSetWeightEnvelopeData
#check selectedCanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData

#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toSharpCutoffMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toExhaustionData

end

end RHFormalization
