import RHFormalization.SelectedFiniteOperatorLayer
import RHFormalization.CanonicalPrimePowerCountingSetEnvelope
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffDisplacementKernel
import RHFormalization.CanonicalPrimePowerExactMassEnvelope

namespace RHFormalization

#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData
#print CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData

#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.W
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.alpha
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.Kshared
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.h_R_ge_nat
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.h_indices_contains_of_center_le_R
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.h_indices_subset_center_le_R
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.kernelID
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.coordSet
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.h_coordSet_compact
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.h_coord_mem

#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData

#check selectedFiniteOperatorLayer
#check sharpCutoffDCanonicalWindowData
#check displacementCanonicalKernel
#check heatKernelG
#check exactPrimePowerMassEnvelopeData

end RHFormalization
