import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummability
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerMassEnvelope

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload
#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability
#check heatKernelWeightedEnvelope_summable

#check heatKernelG
#check displacementCanonicalKernel
#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#check PrimePowerDWindowKernelIdentificationData
#check PrimePowerWeightCutoffEnumerationData
#check PrimePowerMassEnvelopeData

-- Expected unknowns if the selected objects are not built yet:
#check selectedClosedPayload
#check selectedFiniteOperatorLayer
#check selectedH0
#check selectedFH
#check selectedRH
#check selected_sigma0_nonneg

end RHFormalization
