import RHFormalization.SelectedFiniteOperatorLayer
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability
import RHFormalization.CanonicalPrimePowerCutoffMassEnumeration
import RHFormalization.CanonicalPrimePowerMassUpperEnvelope
import RHFormalization.CanonicalPrimePowerExactMassEnvelope
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerSharpCutoffDisplacementKernel

namespace RHFormalization

#check selectedFiniteOperatorLayer
#check selectedFiniteOperatorLayer.toFiniteCanonicalPrimePowerFormula
#check selectedFiniteOperatorLayer.toFiniteCanonicalPrimePowerFormula.indices
#check selectedFiniteOperatorLayer.toFiniteCanonicalPrimePowerFormula.kernel

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload.mk
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#print DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData.mk

#check sharpCutoffDCanonicalWindowData
#print sharpCutoffDCanonicalWindowData

#check PrimePowerDWindowKernelIdentificationData
#print PrimePowerDWindowKernelIdentificationData
#check PrimePowerDWindowKernelIdentificationData.mk

#check PrimePowerWeightCutoffEnumerationData
#print PrimePowerWeightCutoffEnumerationData
#check PrimePowerWeightCutoffEnumerationData.mk

#check exactPrimePowerMassEnvelopeData
#check displacementCanonicalKernel
#check heatKernelG

end RHFormalization
