import RHFormalization
import RHFormalization.DefaultZetaZeroFacts

namespace RHFormalization

#check RH_follows_from_packaged_spine
#print axioms RH_follows_from_packaged_spine

#check ZetaZeroFacts
#check defaultZetaZeroFacts_of_realZeroFree
#print axioms defaultZetaZeroFacts_of_realZeroFree

end RHFormalization
