import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds

#check RHFormalization.PrimePowerCenterCountingSetData
#check RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData

#print RHFormalization.PrimePowerCenterCountingSetData
#print RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData
#print RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData
