import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds

#print RHFormalization.PrimePowerPair
#print RHFormalization.PrimePowerPair.center
#print RHFormalization.PrimePowerWeightCutoffEnumerationData
#print RHFormalization.PrimePowerSoundCutoffEnumerationData
#print RHFormalization.PrimePowerCenterCountingSetData
#print RHFormalization.PrimePowerSoundMassCountingSetWeightEnvelopeData
#print RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData

#check RHFormalization.PrimePowerCenterCountingSetData.countSet
#check RHFormalization.PrimePowerCenterCountingSetData.countEnvelope
#check RHFormalization.PrimePowerCenterCountingSetData.h_center_le_mem_countSet
#check RHFormalization.PrimePowerCenterCountingSetData.h_countSet_card_le_countEnvelope

#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.countBound
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.h_countEnvelope_le_countBound
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.weightBound
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.h_weightEnvelope_le_weightBound
#check RHFormalization.CanonicalPrimePowerDWindowSoundCountingFactorBoundsData.h_countBound_mul_weightBound_div_denominator_tendsto_zero
