import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthSelectedYFromLimits
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthLimits
#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload

end RHFormalization
