import RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimate
import RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeed
import RHFormalization.FinalRHFromDWindowExactMassExactSpeed

#check RHFormalization.exactMass_div_speed_tendsto_zero_of_upper_lower
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimateData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimateData.toExactMassExactSpeedData
#check RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimateData.toExhaustionData
#check RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassSpeedEstimate
#check RHFormalization.canonicalPrimePowerDWindowExactMassSpeedEstimate_h_Bcan_matches_tsum

#print axioms RHFormalization.exactMass_div_speed_tendsto_zero_of_upper_lower
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimateData.toExactMassExactSpeedData
#print axioms RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedEstimateData.toExhaustionData
#print axioms RHFormalization.buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactMassSpeedEstimate
#print axioms RHFormalization.canonicalPrimePowerDWindowExactMassSpeedEstimate_h_Bcan_matches_tsum
