import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed

#check RHFormalization.sharpCutoff_concreteChosenSpeed_pos
#check RHFormalization.sharpCutoff_concreteChosenSpeed_budget
#check RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#check RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeedData.toConcreteCompactSpeedData
#check RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeedData.toCompactSpeedAPI
#check RHFormalization.sharpCutoffConcreteChosen_compact_window_speed_rate

#print axioms RHFormalization.sharpCutoff_concreteChosenSpeed_pos
#print axioms RHFormalization.sharpCutoff_concreteChosenSpeed_budget
#print axioms RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeedData.toConcreteCompactSpeedData
#print axioms RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeedData.toCompactSpeedAPI
#print axioms RHFormalization.sharpCutoffConcreteChosen_compact_window_speed_rate
