import RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeed

#check RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeedData
#check RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeedData.toCompactSpeedData
#check RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeedData.toCompactSpeedAPI
#check RHFormalization.sharpCutoffConcrete_compact_window_speed_rate

#print axioms RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeedData.toCompactSpeedData
#print axioms RHFormalization.DCanonicalWindowSharpCutoffConcreteCompactSpeedData.toCompactSpeedAPI
#print axioms RHFormalization.sharpCutoffConcrete_compact_window_speed_rate
