import RHFormalization.DCanonicalWindowAPIFromCompactSpeed

namespace RHFormalization

#check buildDCanonicalWindowAPIFromCompactSpeed
#print axioms buildDCanonicalWindowAPIFromCompactSpeed

end RHFormalization
