import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDetailedConstruction
import RHFormalization.DFHLimitConcrete
import RHFormalization.DMasterResidualConcrete
import RHFormalization.DResidualSectorBoundsConcrete
import RHFormalization.DFiniteStageOperator

namespace RHFormalization

#check buildDFHLimitDataFromCompactUniform
#check buildDMasterResidualDataFromCompactUniform
#check buildDResidualSectorBoundsAPIFromCompactUniform
#check buildDDetailedConstructionWithOperatorLegalityFromSharpCutoffChosenLengthMassEnvelope

#print DFiniteStagePackageFromOperatorLayer
#print DFiniteStagePackage
#print DCanonicalWindowData
#print DCanonicalWindowAPI
#print DResidualSectorData
#print DResidualSectorSplitAPI
#print DResidualSectorBoundsAPI
#print DMasterResidualAPI
#print DOverlapIdentityAPI

end RHFormalization
