import RHFormalization.DFiniteStageOperator

#check RHFormalization.DFiniteStagePackageFromOperatorLayer.spikeSumData
#check RHFormalization.DFiniteStagePackageFromOperatorLayer.toFiniteCanonicalPrimePowerFormula

#print axioms RHFormalization.DFiniteStagePackageFromOperatorLayer.toFiniteCanonicalPrimePowerFormula
