import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted

namespace RHFormalization

#check ChosenLengthDLimitPayload
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDLimitPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#check buildChosenLengthDLimitPayloadFromHeatKernelWeighted
#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#print axioms buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDLimitPayload
#print axioms buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

end RHFormalization
