import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds
import RHFormalization.CanonicalPrimePowerConcreteCountBound
import RHFormalization.CanonicalPrimePowerConcreteWeightBound
import RHFormalization.CanonicalPrimePowerCountWeightProductBound
import RHFormalization.CanonicalPrimePowerCountWeightQuotient
import RHFormalization.CanonicalPrimePowerMassEnvelopeSpeedComparison
import RHFormalization.CanonicalPrimePowerMassCountingEnvelope
import RHFormalization.CanonicalPrimePowerDWindowCompactRate
import RHFormalization.CanonicalPrimePowerDWindowExactSpeed
import RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeed
import RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudget

namespace RHFormalization

#check countWeight_div_denominator_tendsto_zero_of_cutoff_factor_bounds
#check countWeight_div_denominator_tendsto_zero_of_factor_bounds
#check countWeight_div_denominator_tendsto_zero_of_numerator_bound

#check CanonicalPrimePowerDWindowSoundCountingFactorBoundsData
#print CanonicalPrimePowerDWindowSoundCountingFactorBoundsData

#check DCanonicalWindowCompactSpeedAPI
#print DCanonicalWindowCompactSpeedAPI

#check CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData
#print CanonicalPrimePowerDWindowMassEnvelopeSpeedComparisonData

#check CanonicalPrimePowerDWindowMassCountingEnvelopeData
#print CanonicalPrimePowerDWindowMassCountingEnvelopeData

#check concreteCountBound
#check concreteWeightBound
#check countEnvelope_le_concreteCountBound
#check weightEnvelope_le_concreteWeightBound

end RHFormalization
