import RHFormalization.CanonicalPrimePowerMassUpperEnvelope
import RHFormalization.CanonicalPrimePowerSharpCutoffMassEnvelope
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope
import RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeed
import RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeed

namespace RHFormalization

#check CanonicalPrimePowerDWindowMassUpperEnvelopeData
#print CanonicalPrimePowerDWindowMassUpperEnvelopeData

#check CanonicalPrimePowerSharpCutoffMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffMassEnvelopeData

#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#print CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData

#check CanonicalPrimePowerDWindowExactWindowSpeedData
#print CanonicalPrimePowerDWindowExactWindowSpeedData

#check CanonicalPrimePowerDWindowExactMassExactSpeedData
#print CanonicalPrimePowerDWindowExactMassExactSpeedData

end RHFormalization
