import RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeed
import RHFormalization.CanonicalPrimePowerDWindowExactSpeed
import RHFormalization.CanonicalPrimePowerDWindowExactMassSpeedBudget
import RHFormalization.CanonicalPrimePowerMassCountingEnvelope
import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds

namespace RHFormalization

#check DCanonicalWindowCompactSpeedAPI
#print DCanonicalWindowCompactSpeedAPI

#check CanonicalPrimePowerDWindowExactWindowSpeedData
#print CanonicalPrimePowerDWindowExactWindowSpeedData

#check CanonicalPrimePowerDWindowMassCountingSpeedComparisonData
#print CanonicalPrimePowerDWindowMassCountingSpeedComparisonData

#check CanonicalPrimePowerDWindowSoundCountingFactorBoundsData
#print CanonicalPrimePowerDWindowSoundCountingFactorBoundsData

end RHFormalization
