import RHFormalization.CanonicalPrimePowerExhaustion
import RHFormalization.CanonicalPrimePowerRCutoffExhaustion
import RHFormalization.CanonicalPrimePowerRCutoffRatePackaged
import RHFormalization.CanonicalPrimePowerRCutoffMassBound
import RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowth

#check RHFormalization.CanonicalPrimePowerExhaustionData
#check RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit

#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData

#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData
#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData

#check RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData.toExhaustionData

#print RHFormalization.CanonicalPrimePowerExhaustionData
#print RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData
#print RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData
#print RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData

#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData.toExhaustionData
