import RHFormalization.FinalRHFromDWindowExactMassExactSpeed

#check RHFormalization.DWindowExactMassExactSpeedSharedPackage
#check RHFormalization.DWindowExactMassExactSpeedFiniteCanonicalLimit
#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
#check RHFormalization.detailedConstructionFromDWindowExactMassExactSpeed_Bcan_matches_tsum
#check RHFormalization.finalRHSpine_from_DWindowExactMassExactSpeedData

#print axioms RHFormalization.DWindowExactMassExactSpeedFiniteCanonicalLimit
#print axioms RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
#print axioms RHFormalization.detailedConstructionFromDWindowExactMassExactSpeed_Bcan_matches_tsum
#print axioms RHFormalization.finalRHSpine_from_DWindowExactMassExactSpeedData
