import RHFormalization.SelectedFiniteTraceSpikePayloadFromImageBridge
import RHFormalization.CanonicalPrimePowerConcreteTsumPackage
import RHFormalization.CanonicalPrimePowerKernelSeries
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerIndexExhaustion
import RHFormalization.AppendixDSpikeSumExtraction
import RHFormalization.DFiniteStageOperator

namespace RHFormalization

#check buildSelectedFiniteTraceSpikePayloadFromImageBridge
#check buildDFiniteStageCanonicalPrimePowerFormulaFromSpikeSums

#check DFiniteTraceFunctionData.mk
#check DFiniteStageSplitAPI.mk
#check DFiniteStageSplitFromDuhamelAPI.mk
#check DFiniteStageSpikeSumData.mk

#check finiteNatSpikePackage
#check finiteCanonicalPrimePowerPackage
#check finiteNatSpikePackage_eq_finiteCanonicalPrimePowerPackage_image

#check PrimePowerPair
#check PrimePowerPair.center
#check PrimePowerPair.weightC

end RHFormalization
