import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityClosure
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerMassEnvelope
import RHFormalization.CanonicalPrimePowerCutoffMassEnumeration

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check heatKernelWeightedEnvelope_summable
#check heatKernelG

#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#print DCanonicalWindowSharpCutoffConcreteChosenSpeedData

#check PrimePowerDWindowKernelIdentificationData
#print PrimePowerDWindowKernelIdentificationData

#check PrimePowerWeightCutoffEnumerationData
#print PrimePowerWeightCutoffEnumerationData

#check PrimePowerMassEnvelopeData
#print PrimePowerMassEnvelopeData

end RHFormalization
