import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffHeatKernelWeighted
#check canonicalPrimePowerSharpCutoffHeatKernelWeighted_h_Bcan_matches_tsum

-- Useful already-closed summability input.
#check heatKernelWeightedEnvelope_summable

end RHFormalization
