import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummability
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerMassEnvelope

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload
#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability

#check heatKernelWeightedEnvelope_summable
#check heatKernelG
#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#check PrimePowerDWindowKernelIdentificationData
#check PrimePowerWeightCutoffEnumerationData
#check PrimePowerMassEnvelopeData

end RHFormalization
