import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload.toHeatKernelWeightedData
#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload

#print axioms CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload.toHeatKernelWeightedData
#print axioms buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload

end RHFormalization
