import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability

namespace RHFormalization

#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability
#print axioms buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataClosedSummability

end RHFormalization
