import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityTarget
import RHFormalization.CanonicalPrimePowerHeatKernelWeightedSummabilityClosure

namespace RHFormalization

#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedData

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExactWeightedEnvelopeData
#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffHeatKernelWeighted
#check canonicalPrimePowerSharpCutoffHeatKernelWeighted_h_Bcan_matches_tsum

#check heatKernelWeightedEnvelope_summable

end RHFormalization
