import RHFormalization.HExplicitFormulaWitnessBranchFromPrincipalParts

#check RHFormalization.Harch_witness_extensions_from_Bshared_opposite_principalParts
#check RHFormalization.Harch_holomorphic_from_principalParts_and_regular

#print axioms RHFormalization.Harch_witness_extensions_from_Bshared_opposite_principalParts
#print axioms RHFormalization.Harch_holomorphic_from_principalParts_and_regular
