import RHFormalization.HMeromorphicWithNormalFormChosenCshared

#check RHFormalization.buildHMeromorphicWithNormalFormPolesWithChosenCshared
#check RHFormalization.buildHMeromorphicWithNormalFormPolesWithChosenCshared_Cshared_eq
#check RHFormalization.finalRHSpine_from_HChosenDSharedC

#print axioms RHFormalization.buildHMeromorphicWithNormalFormPolesWithChosenCshared
#print axioms RHFormalization.buildHMeromorphicWithNormalFormPolesWithChosenCshared_Cshared_eq
#print axioms RHFormalization.finalRHSpine_from_HChosenDSharedC
