import RHFormalization.OmegaNormalFormLocalPropagationEndpoint

#check RHFormalization.finalConditionalRHSpine_localNormalFormPropagation
#print axioms RHFormalization.finalConditionalRHSpine_localNormalFormPropagation
#print RHFormalization.OmegaNormalFormLocalPropagationAPI
