import RHFormalization.CanonicalPrimePowerHeatKernelNatValueMajorantSummability
import Mathlib.Analysis.PSeries

#check Real.summable_nat_pow_inv
#check Real.summable_one_div_nat_add_rpow
#check Summable.of_nonneg_of_le
#check Summable.mul_left
#check Summable.prod
#check summable_nat_add_iff

#check RHFormalization.heatKernelNatValueMajorant_summable_of_model
#check RHFormalization.heatKernelNatValueMajorant_eq_zero_of_not_isPrimePowerPair
#check RHFormalization.heatKernelNatValueMajorant_eq_valid_primePower_formula
#check RHFormalization.norm_weightC_eq_abs_weightReal
#check RHFormalization.PrimePowerPair.natValue
#check RHFormalization.PrimePowerPair.weightReal
#check RHFormalization.PrimePowerPair.weightC
#check RHFormalization.IsPrimePowerPair
