import RHFormalization.OmegaPuncturedIdentityEndpoint

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity
