import RHFormalization.OmegaCodiscreteIdentityFromNormalForms

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormCodiscreteIdentity
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormCodiscreteIdentity
