import RHFormalization.DefaultOmegaPreperfect

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_codiscreteIdentity_preperfect
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_codiscreteIdentity_preperfect
