import RHFormalization.OmegaPuncturedIdentityFromCodiscrete

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_codiscreteIdentity
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_codiscreteIdentity
