import RHFormalization

#check RHFormalization.DOperatorFiniteCanonicalLimitAtOverlapData
#check RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit
#check RHFormalization.buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
#check RHFormalization.finalRHSpine_after_sharedPackageFunctionalCompatibility

#print RHFormalization.DOperatorFiniteCanonicalLimitAtOverlapData
#print RHFormalization.CanonicalPrimePowerExhaustionData
#print RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit

#print axioms RHFormalization.CanonicalPrimePowerExhaustionData.toDOperatorFiniteCanonicalLimit
#print axioms RHFormalization.buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
#print axioms RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
#print axioms RHFormalization.finalRHSpine_after_sharedPackageFunctionalCompatibility
