import RHFormalization.ONFPLocalFrequent

#check RHFormalization.eventuallyEq_nhdsNE_of_eventuallyEq_codiscreteWithin_of_mem_open
#check RHFormalization.frequently_eq_nhdsNE_of_eventuallyEq_codiscreteWithin_of_mem_open

#print axioms RHFormalization.eventuallyEq_nhdsNE_of_eventuallyEq_codiscreteWithin_of_mem_open
#print axioms RHFormalization.frequently_eq_nhdsNE_of_eventuallyEq_codiscreteWithin_of_mem_open
