import RHFormalization.InterfaceBridgeNonnegativeFromPlain

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormPropagation_plainInterface
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormPropagation_plainInterface
