import RHFormalization.PrincipalPartOrderFromCobounded

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_principalPartCobounded
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_principalPartCobounded
