import RHFormalization.PrincipalPartMeromorphic

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_principalPartCobounded_only
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_principalPartCobounded_only
