import RHFormalization.PuncturedMeromorphicIdentityEndpoint
import RHFormalization.OmegaPuncturedIdentityEndpoint
import RHFormalization.OmegaPuncturedIdentityFromCodiscrete
import RHFormalization.DefaultZetaZeroFacts

namespace RHFormalization

#check PuncturedMeromorphicIdentityAPI
#print PuncturedMeromorphicIdentityAPI

#check OmegaPuncturedMeromorphicIdentityAPI
#print OmegaPuncturedMeromorphicIdentityAPI

#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_puncturedIdentity
#print axioms mainTheorem_from_default_connectedOmega_meromorphicAlgebra_puncturedIdentity

#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity
#print axioms mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity

#check buildOmegaPuncturedIdentityFromCodiscrete
#print axioms buildOmegaPuncturedIdentityFromCodiscrete

#check defaultZetaZeroFacts_of_realZeroFree

end RHFormalization
