import RHFormalization.PuncturedIdentityLocalCore
import RHFormalization.DefaultDenominatorSimpleZeroOrder
import RHFormalization.MainTheorem
import RHFormalization.PoleObstructionFromNormalForm
import RHFormalization.PoleNormalForm
import RHFormalization.RigidityBridge
import RHFormalization.GlobalRigidity

#print RHFormalization.RiemannHypothesis
#check RHFormalization.mkZeroWitness
#check RHFormalization.no_ZeroWitness_of_rigidity

#print RHFormalization.mainTheorem_from_theorem_backed_Omega
#print RHFormalization.mainTheorem_from_H_grouped_pole_layer

#check RHFormalization.HMeromorphicWithNormalFormPoles.toLegacyZeroPolePackageAPI
#check RHFormalization.HMeromorphicWithNormalFormPoles.toLegacyGenuinePoleNormalFormAPI
#check RHFormalization.HMeromorphicWithNormalFormPoles.toPoleNormalFormLayer
#check RHFormalization.principalPartNormalFormOfGenuine

#check RHFormalization.PuncturedMeromorphicIdentityAPI.h_punctured_identity
#check RHFormalization.local_order_obstruction_from_punctured_holomorphic_balance
