import RHFormalization.CanonicalPrimePowerSharpCutoffClosedDWindowSource
import RHFormalization.AppendixDRCutoffEstimateDetailedConstruction
import RHFormalization.CanonicalPrimePowerCountingSetEnvelope

namespace RHFormalization

#check CanonicalPrimePowerRCutoffMassGrowthWindowData
#print CanonicalPrimePowerRCutoffMassGrowthWindowData

#check RCutoffEstimateSharedPackage
#check RCutoffEstimateFiniteCanonicalLimit

#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toMassCountingWeightEnvelopeData
#check CanonicalPrimePowerDWindowMassCountingSetWeightEnvelopeData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerDWindowMassCountingSetWeightEnvelope

-- Try likely projections/converters from the R-cutoff package.
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.W
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.alpha
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.Kshared
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.massEnum
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.kernelID
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.coordSet
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.h_coordSet_compact
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.h_coord_mem
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.h_R_ge_nat
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.h_indices_contains_of_center_le_R
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.h_indices_subset_center_le_R
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.toMassCountingSetWeightEnvelopeData
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.toDWindowMassCountingSetWeightEnvelopeData
#check CanonicalPrimePowerRCutoffMassGrowthWindowData.toDWindowData

end RHFormalization
