import RHFormalization.CanonicalPrimePowerRCutoffExhaustion
import RHFormalization.CanonicalPrimePowerRCutoffGrowth
import RHFormalization.CanonicalPrimePowerRCutoffRatePackaged
import RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowth
import RHFormalization.FinalRHFromRCutoffEstimate

#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData
#check RHFormalization.canonicalPrimePowerRCutoffMassGrowthWindow_h_Bcan_matches_tsum

#check RHFormalization.CanonicalPrimePowerRCutoffGrowthMassWindowData
#check RHFormalization.CanonicalPrimePowerRCutoffGrowthMassWindowData.toExhaustionData

#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData
#check RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData

#check RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData
#check RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData.toExhaustionData

#check RHFormalization.RCutoffEstimateFiniteCanonicalLimit
#check RHFormalization.buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
#check RHFormalization.finalRHSpine_from_RCutoffEstimateData

#print RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData
#print RHFormalization.CanonicalPrimePowerRCutoffGrowthMassWindowData
#print RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData
#print RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData

#print axioms RHFormalization.CanonicalPrimePowerRCutoffMassGrowthWindowData.toExhaustionData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffGrowthMassWindowData.toExhaustionData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffRatePackagedData.toExhaustionData
#print axioms RHFormalization.CanonicalPrimePowerRCutoffRateMassGrowthData.toExhaustionData
#print axioms RHFormalization.RCutoffEstimateFiniteCanonicalLimit
#print axioms RHFormalization.finalRHSpine_from_RCutoffEstimateData
