import RHFormalization.AppendixDRCutoffEstimateDetailedConstruction
import RHFormalization.SelectedFiniteOperatorLayer
import RHFormalization.CanonicalPrimePowerSharpCutoffClosedDWindowSource

namespace RHFormalization

#check CanonicalPrimePowerRCutoffMassGrowthWindowData
#check RCutoffEstimateSharedPackage
#check RCutoffEstimateFiniteCanonicalLimit

#check detailedConstructionFromRCutoffEstimate
#check detailedConstructionFromRCutoffEstimate_Bcan_matches_tsum

#check DDetailedConstructionWithOperatorLegality
#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload
#check buildDDetailedConstructionWithOperatorLegalityFromChosenLengthDLimitPayload
#check buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate

-- Try likely selected names.
#check selectedRCutoffMassGrowthWindowData
#check selectedRCutoffEstimateData
#check selectedRCutoffEstimate
#check selectedDetailedConstructionFromRCutoffEstimate
#check selectedDDetailedConstructionWithOperatorLegality

end RHFormalization
