import RHFormalization.CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthDLimitPayloadFromHeatKernelWeighted
import RHFormalization.DCanonicalWindowSharpCutoffConcreteChosenSpeed
import RHFormalization.CanonicalPrimePowerDWindowKernelIdentification
import RHFormalization.CanonicalPrimePowerMassEnvelope
import RHFormalization.CanonicalPrimePowerCutoffMassEnumeration

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload
#print CanonicalPrimePowerSharpCutoffHeatKernelWeightedClosedPayload

#check buildCanonicalPrimePowerSharpCutoffHeatKernelWeightedDataFromClosedPayload
#check buildDDetailedConstructionWithOperatorLegalityFromHeatKernelWeightedPayload

#check DFiniteStagePackageFromOperatorLayer
#check heatKernelG
#check DCanonicalWindowSharpCutoffConcreteChosenSpeedData
#check PrimePowerDWindowKernelIdentificationData
#check PrimePowerWeightCutoffEnumerationData
#check PrimePowerMassEnvelopeData

end RHFormalization
