import RHFormalization.SelectedFiniteCanonicalPayload

namespace RHFormalization

#check SelectedFiniteCanonicalPayload
#check buildSelectedFiniteOperatorLayerFromCanonicalPayload
#print axioms buildSelectedFiniteOperatorLayerFromCanonicalPayload

end RHFormalization
