import RHFormalization.SelectedFiniteTraceSpikePayload
import RHFormalization.AppendixDSpikeSumExtraction
import RHFormalization.AppendixDPrimePowerFiniteFormulaTarget
import RHFormalization.AppendixDPrimePowerLimitComparison
import RHFormalization.AppendixDPrimePowerLimitReduction
import RHFormalization.AppendixDOperatorPrimePowerToDBcan

namespace RHFormalization

#check SelectedFiniteTraceSpikePayload
#print SelectedFiniteTraceSpikePayload

-- The one missing selected object.
#check selectedFiniteTraceSpikePayload

-- Existing generic spike-sum bridge tools.
#check finiteNatSpikePackage
#check finiteNatSpikePackage_eq_of_coeff_eq_on_indices
#check DFiniteStageSpikeSumData
#print DFiniteStageSpikeSumData
#check buildDFiniteStageCanonicalPrimePowerFormulaFromSpikeSums

-- Prime-power finite formula / B-stage tools.
#check DFiniteStageCanonicalPrimePowerFormula
#print DFiniteStageCanonicalPrimePowerFormula
#check finiteCanonicalPrimePowerPackage

-- Limit-side tools that consume the finite formula.
#check buildDOperatorPrimePowerLimitAtOverlapData_fromFiniteCanonicalLimit
#check buildDBcanLimitDataFromOperatorFiniteCanonicalLimit

end RHFormalization
