import RHFormalization.SelectedFiniteTraceSpikePayloadCertified

namespace RHFormalization

#check IsCertifiedFiniteAppendixDExtraction
#print IsCertifiedFiniteAppendixDExtraction

#check CertifiedSelectedFiniteTraceSpikePayload
#check buildSelectedFiniteOperatorLayerFromCertifiedTraceSpikePayload
#print axioms buildSelectedFiniteOperatorLayerFromCertifiedTraceSpikePayload

end RHFormalization
