import RHFormalization.DefaultSimplePoleCoboundedFromOrder

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_simplePoleOrder
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_simplePoleOrder
