import RHFormalization.PrincipalPartCoboundedModel

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_simplePoleCobounded
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_and_simplePoleCobounded
