import RHFormalization.OmegaNormalFormPropagationEndpoint

#check RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormPropagation
#print axioms RHFormalization.mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormPropagation
