import RHFormalization.CanonicalPrimePowerRCutoffExhaustion
import RHFormalization.AppendixDOperatorFiniteCanonicalDetailedConstruction

/-!
# RHFormalization.AppendixDRCutoffEstimateDetailedConstruction

Composes the sharp R-cutoff / mass-growth / window-error D-side estimate package
into the detailed Appendix-D construction.

This is not an RH endpoint.

It wires the current sharpest canonical prime-power finite-to-limit estimate data

  `CanonicalPrimePowerRCutoffMassGrowthWindowData`

into

  `DDetailedConstructionWithOperatorLegality`.

After this file, the D-side prime-power estimate obligations feed the D/E/F
spine directly rather than only existing as standalone reduction layers.
-/

namespace RHFormalization

noncomputable section

open Complex Topology Filter
open scoped BigOperators

/--
The canonical shared package generated by the R-cutoff estimate data.
-/
abbrev RCutoffEstimateSharedPackage
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerRCutoffMassGrowthWindowData finiteOperatorLayer) :
    CanonicalPrimePowerPackage :=
  canonicalPrimePowerPackageFromKernelTsum
    finiteOperatorLayer.toStagePackage.sigma0
    S.Kshared

/--
The finite-canonical convergence data generated by the R-cutoff estimate data.
-/
abbrev RCutoffEstimateFiniteCanonicalLimit
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerRCutoffMassGrowthWindowData finiteOperatorLayer) :
    DOperatorFiniteCanonicalLimitAtOverlapData
      finiteOperatorLayer
      (RCutoffEstimateSharedPackage finiteOperatorLayer S) :=
  S.toExhaustionData.toDOperatorFiniteCanonicalLimit

/--
Build the detailed Appendix-D construction directly from the sharp R-cutoff /
mass-growth / window-error estimate package.

This composes:

  R-cutoff estimate data
    → canonical prime-power exhaustion data
    → finite canonical limit data
    → DBcanLimitData
    → DDetailedConstructionWithOperatorLegality.
-/
def buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerRCutoffMassGrowthWindowData finiteOperatorLayer)
    (W : DCanonicalWindowData)
    (Wapi : DCanonicalWindowAPI W)
    (F : DFHLimitData finiteOperatorLayer.toStagePackage)
    (sectors : DResidualSectorData finiteOperatorLayer.toStagePackage)
    (sectorSplit :
      DResidualSectorSplitAPI finiteOperatorLayer.toStagePackage sectors)
    (sectorBounds :
      DResidualSectorBoundsAPI finiteOperatorLayer.toStagePackage sectors)
    (master :
      DMasterResidualAPI finiteOperatorLayer.toStagePackage sectors)
    (overlapBuilder :
      let Cshared := RCutoffEstimateSharedPackage finiteOperatorLayer S
      let finiteCanonicalLimit :=
        RCutoffEstimateFiniteCanonicalLimit finiteOperatorLayer S
      let Bdata :=
        buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
          finiteOperatorLayer
          Cshared
          finiteCanonicalLimit
      let Rdata := master.h_master sectorSplit sectorBounds
      DOverlapIdentityAPI
        finiteOperatorLayer.toStagePackage
        Bdata
        F
        Rdata) :
    DDetailedConstructionWithOperatorLegality :=
  buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
    finiteOperatorLayer
    (RCutoffEstimateSharedPackage finiteOperatorLayer S)
    (RCutoffEstimateFiniteCanonicalLimit finiteOperatorLayer S)
    W
    Wapi
    F
    sectors
    sectorSplit
    sectorBounds
    master
    overlapBuilder

/--
The D-side `Bcan` produced from R-cutoff estimate data agrees with the concrete
tsum-defined shared package.
-/
theorem detailedConstructionFromRCutoffEstimate_Bcan_matches_tsum
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerRCutoffMassGrowthWindowData finiteOperatorLayer)
    (W : DCanonicalWindowData)
    (Wapi : DCanonicalWindowAPI W)
    (F : DFHLimitData finiteOperatorLayer.toStagePackage)
    (sectors : DResidualSectorData finiteOperatorLayer.toStagePackage)
    (sectorSplit :
      DResidualSectorSplitAPI finiteOperatorLayer.toStagePackage sectors)
    (sectorBounds :
      DResidualSectorBoundsAPI finiteOperatorLayer.toStagePackage sectors)
    (master :
      DMasterResidualAPI finiteOperatorLayer.toStagePackage sectors)
    (overlapBuilder :
      let Cshared := RCutoffEstimateSharedPackage finiteOperatorLayer S
      let finiteCanonicalLimit :=
        RCutoffEstimateFiniteCanonicalLimit finiteOperatorLayer S
      let Bdata :=
        buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
          finiteOperatorLayer
          Cshared
          finiteCanonicalLimit
      let Rdata := master.h_master sectorSplit sectorBounds
      DOverlapIdentityAPI
        finiteOperatorLayer.toStagePackage
        Bdata
        F
        Rdata)
    (s : ℂ)
    (hs : s ∈ RightHalfPlane finiteOperatorLayer.toStagePackage.sigma0) :
    (buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
      finiteOperatorLayer
      S
      W
      Wapi
      F
      sectors
      sectorSplit
      sectorBounds
      master
      overlapBuilder).B.Bcan s =
      ∑' q : PrimePowerPair,
        q.weightC * S.Kshared q.center s := by
  have hshared :
      (buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
        finiteOperatorLayer
        S
        W
        Wapi
        F
        sectors
        sectorSplit
        sectorBounds
        master
        overlapBuilder).B.Bcan s =
        (RCutoffEstimateSharedPackage finiteOperatorLayer S).Bshared s := by
    exact
      (buildDDetailedConstructionWithOperatorLegalityFromRCutoffEstimate
        finiteOperatorLayer
        S
        W
        Wapi
        F
        sectors
        sectorSplit
        sectorBounds
        master
        overlapBuilder).B.h_Bcan_matches_shared s hs

  simpa [RCutoffEstimateSharedPackage, canonicalPrimePowerPackageFromKernelTsum]
    using hshared

end

end RHFormalization
