import RHFormalization.CanonicalPrimePowerSharpCutoffSharedLimitMajorant

/-!
# RHFormalization.CanonicalPrimePowerSharpCutoffDisplacementKernel

Displacement-kernel specialization of the sharp-cutoff chosen-length branch.

This removes the field

  h_sharedKernel_norm_le_majorant

by specializing the shared kernel to the displacement-only kernel

  Kshared a s := G a

and choosing

  kernelMajorant q := ‖G q.center‖.

This is not an endpoint theorem. It removes a live majorant field from the
current sharp-cutoff branch.
-/

namespace RHFormalization

noncomputable section

open Complex Topology Filter
open scoped BigOperators

/--
The displacement-only shared canonical kernel generated by `G`.

This is the natural shape for the canonical heat/displacement kernel:
the shared kernel depends on the displacement coordinate `a`, not directly on
the complex spectral parameter `s`.
-/
def displacementCanonicalKernel
    (G : ℝ → ℂ) :
    CanonicalKernelC :=
  fun a _s => G a

/--
The exact norm majorant attached to the displacement kernel.
-/
def displacementKernelMajorant
    (G : ℝ → ℂ)
    (q : PrimePowerPair) :
    ℝ :=
  ‖G q.center‖

/--
The displacement-kernel majorant is nonnegative.
-/
theorem displacementKernelMajorant_nonneg
    (G : ℝ → ℂ) :
    ∀ q : PrimePowerPair,
      0 ≤ displacementKernelMajorant G q := by
  intro q
  exact norm_nonneg (G q.center)

/--
For the displacement-only kernel `Kshared a s := G a`, the shared-kernel
majorant is immediate from the chosen majorant `‖G q.center‖`.
-/
theorem displacementKernel_sharedKernel_norm_le_majorant
    (G : ℝ → ℂ)
    (sigma0 : ℝ) :
    ∀ s : ℂ,
    ∀ hs : s ∈ RightHalfPlane sigma0,
    ∀ q : PrimePowerPair,
      ‖(displacementCanonicalKernel G) q.center s‖
        ≤ displacementKernelMajorant G q := by
  intro s hs q
  dsimp [displacementCanonicalKernel, displacementKernelMajorant]
  exact le_rfl

/--
Sharp-cutoff chosen-length data with displacement-only shared kernel.

Compared with
`CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData`, this structure
does not ask for:

* `Kshared`;
* `kernelMajorant`;
* `h_kernelMajorant_nonneg`;
* `h_sharedKernel_norm_le_majorant`.

They are supplied by:

  Kshared q.center s := G q.center
  kernelMajorant q := ‖G q.center‖.
-/
structure CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData
    (X : DFiniteStagePackageFromOperatorLayer) where

  G : ℝ → ℂ
  Lstage : DFiniteStage → ℝ
  alpha : ℕ → DFiniteStage

  sharpSpeed :
    DCanonicalWindowSharpCutoffConcreteChosenSpeedData G Lstage alpha

  h_R_ge_nat :
    ∀ n : ℕ, (n : ℝ) ≤ (alpha n).R

  h_indices_contains_of_center_le_R :
    ∀ n : ℕ,
    ∀ q : PrimePowerPair,
      q.center ≤ (alpha n).R →
        q ∈ X.toFiniteCanonicalPrimePowerFormula.indices (alpha n)

  h_indices_subset_center_le_R :
    ∀ n : ℕ,
    ∀ q : PrimePowerPair,
      q ∈ X.toFiniteCanonicalPrimePowerFormula.indices (alpha n) →
        q.center ≤ (alpha n).R

  kernelID :
    PrimePowerDWindowKernelIdentificationData
      X
      (sharpCutoffDCanonicalWindowData G Lstage)
      alpha
      (displacementCanonicalKernel G)

  coordSet : ℂ → Set ℝ

  h_coordSet_compact :
    ∀ s : ℂ,
    ∀ hs : s ∈ RightHalfPlane X.toStagePackage.sigma0,
      IsCompact (coordSet s)

  h_coord_mem :
    ∀ s : ℂ,
    ∀ hs : s ∈ RightHalfPlane X.toStagePackage.sigma0,
    ∀ n : ℕ,
    ∀ q : PrimePowerPair,
      q ∈ X.toFiniteCanonicalPrimePowerFormula.indices (alpha n) →
        kernelID.coord s q ∈ coordSet s

  summabilityEnvelope : PrimePowerPair → ℝ

  h_weightedKernelMajorant_le_envelope :
    ∀ q : PrimePowerPair,
      ‖q.weightC‖ * displacementKernelMajorant G q
        ≤ summabilityEnvelope q

  h_summabilityEnvelope_summable :
    Summable summabilityEnvelope

  massEnum : PrimePowerWeightCutoffEnumerationData

  massEnvelopeData : PrimePowerMassEnvelopeData massEnum

  hL_chosen :
    ∀ n : ℕ,
      Lstage (alpha n) =
        (massEnvelopeData.massEnvelope ((alpha n).R) + 1) *
          ((n : ℝ) + 1)

/--
Convert displacement-kernel data into the shared-majorant chosen-length package.

This is where `h_sharedKernel_norm_le_majorant` and
`h_kernelMajorant_nonneg` are discharged.
-/
def CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData.toSharedMajorantData
    {X : DFiniteStagePackageFromOperatorLayer}
    (S : CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData X) :
    CanonicalPrimePowerSharpCutoffChosenLengthSharedMajorantData X :=
  { G := S.G
    Lstage := S.Lstage
    alpha := S.alpha

    sharpSpeed := S.sharpSpeed

    Kshared := displacementCanonicalKernel S.G

    h_R_ge_nat := S.h_R_ge_nat
    h_indices_contains_of_center_le_R :=
      S.h_indices_contains_of_center_le_R
    h_indices_subset_center_le_R :=
      S.h_indices_subset_center_le_R

    kernelMajorant := displacementKernelMajorant S.G
    h_kernelMajorant_nonneg :=
      displacementKernelMajorant_nonneg S.G

    kernelID := S.kernelID
    coordSet := S.coordSet
    h_coordSet_compact := S.h_coordSet_compact
    h_coord_mem := S.h_coord_mem

    h_sharedKernel_norm_le_majorant :=
      displacementKernel_sharedKernel_norm_le_majorant
        S.G
        X.toStagePackage.sigma0

    summabilityEnvelope := S.summabilityEnvelope
    h_weightedKernelMajorant_le_envelope :=
      S.h_weightedKernelMajorant_le_envelope
    h_summabilityEnvelope_summable :=
      S.h_summabilityEnvelope_summable

    massEnum := S.massEnum
    massEnvelopeData := S.massEnvelopeData
    hL_chosen := S.hL_chosen }

/--
Build `CanonicalPrimePowerExhaustionData` from displacement-kernel data.
-/
def CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData.toExhaustionData
    {X : DFiniteStagePackageFromOperatorLayer}
    (S : CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData X) :
    CanonicalPrimePowerExhaustionData
      X
      (canonicalPrimePowerPackageFromKernelTsum
        X.toStagePackage.sigma0
        (displacementCanonicalKernel S.G)) :=
  S.toSharedMajorantData.toExhaustionData

/--
Build `DBcanLimitData` from displacement-kernel data.
-/
def buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernel
    (X : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData X) :
    DBcanLimitData X.toStagePackage :=
  buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthSharedMajorant
    X
    S.toSharedMajorantData

/--
The D-side canonical package matches the concrete displacement-kernel tsum package.
-/
theorem canonicalPrimePowerSharpCutoffChosenLengthDisplacementKernel_h_Bcan_matches_tsum
    (X : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernelData X)
    (s : ℂ)
    (hs : s ∈ RightHalfPlane X.toStagePackage.sigma0) :
    (buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthDisplacementKernel X S).Bcan s =
      ∑' q : PrimePowerPair,
        q.weightC * (displacementCanonicalKernel S.G) q.center s := by
  exact
    canonicalPrimePowerSharpCutoffChosenLengthSharedMajorant_h_Bcan_matches_tsum
      X
      S.toSharedMajorantData
      s
      hs

end

end RHFormalization
