import RHFormalization.CanonicalPrimePowerDWindowExactMassExactSpeed
import RHFormalization.AppendixDOperatorFiniteCanonicalDetailedConstruction
import RHFormalization.AppendixESharedPackageFunctionalCompatibility

/-!
# RHFormalization.FinalRHFromDWindowExactMassExactSpeed

Current sharpest formal RH frontier.

This file is not a new proof shortcut.

It wires the current sharpest D-side estimate package,

  `CanonicalPrimePowerDWindowExactMassExactSpeedData`,

into the detailed Appendix-D construction and then into the final E/F RH spine.

After this file, the remaining mathematical work is to construct the exact
mass/exact speed data fields:
* compact D-window inverse-speed rate;
* exact prime-power mass divided by speed tends to zero;
* shared kernel majorant;
* weighted summability.
-/

namespace RHFormalization

noncomputable section

open Complex Topology Filter
open scoped BigOperators

/--
The shared canonical package generated by exact-mass/exact-speed D-window data.
-/
abbrev DWindowExactMassExactSpeedSharedPackage
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerDWindowExactMassExactSpeedData finiteOperatorLayer) :
    CanonicalPrimePowerPackage :=
  canonicalPrimePowerPackageFromKernelTsum
    finiteOperatorLayer.toStagePackage.sigma0
    S.Kshared

/--
The finite-canonical limit generated by exact-mass/exact-speed D-window data.
-/
abbrev DWindowExactMassExactSpeedFiniteCanonicalLimit
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerDWindowExactMassExactSpeedData finiteOperatorLayer) :
    DOperatorFiniteCanonicalLimitAtOverlapData
      finiteOperatorLayer
      (DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S) :=
  S.toExhaustionData.toDOperatorFiniteCanonicalLimit

/--
Build the detailed Appendix-D construction directly from exact-mass/exact-speed
D-window estimate data.
-/
def buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerDWindowExactMassExactSpeedData finiteOperatorLayer)
    (W : DCanonicalWindowData)
    (Wapi : DCanonicalWindowAPI W)
    (F : DFHLimitData finiteOperatorLayer.toStagePackage)
    (sectors : DResidualSectorData finiteOperatorLayer.toStagePackage)
    (sectorSplit :
      DResidualSectorSplitAPI finiteOperatorLayer.toStagePackage sectors)
    (sectorBounds :
      DResidualSectorBoundsAPI finiteOperatorLayer.toStagePackage sectors)
    (master :
      DMasterResidualAPI finiteOperatorLayer.toStagePackage sectors)
    (overlapBuilder :
      let Cshared := DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S
      let finiteCanonicalLimit :=
        DWindowExactMassExactSpeedFiniteCanonicalLimit finiteOperatorLayer S
      let Bdata :=
        buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
          finiteOperatorLayer
          Cshared
          finiteCanonicalLimit
      let Rdata := master.h_master sectorSplit sectorBounds
      DOverlapIdentityAPI
        finiteOperatorLayer.toStagePackage
        Bdata
        F
        Rdata) :
    DDetailedConstructionWithOperatorLegality :=
  buildDDetailedConstructionWithOperatorLegalityFromFiniteCanonicalLimit
    finiteOperatorLayer
    (DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S)
    (DWindowExactMassExactSpeedFiniteCanonicalLimit finiteOperatorLayer S)
    W
    Wapi
    F
    sectors
    sectorSplit
    sectorBounds
    master
    overlapBuilder

/--
The detailed D construction produced from exact-mass/exact-speed D-window data
has `Bcan` equal to the concrete tsum-defined shared package.
-/
theorem detailedConstructionFromDWindowExactMassExactSpeed_Bcan_matches_tsum
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerDWindowExactMassExactSpeedData finiteOperatorLayer)
    (W : DCanonicalWindowData)
    (Wapi : DCanonicalWindowAPI W)
    (F : DFHLimitData finiteOperatorLayer.toStagePackage)
    (sectors : DResidualSectorData finiteOperatorLayer.toStagePackage)
    (sectorSplit :
      DResidualSectorSplitAPI finiteOperatorLayer.toStagePackage sectors)
    (sectorBounds :
      DResidualSectorBoundsAPI finiteOperatorLayer.toStagePackage sectors)
    (master :
      DMasterResidualAPI finiteOperatorLayer.toStagePackage sectors)
    (overlapBuilder :
      let Cshared := DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S
      let finiteCanonicalLimit :=
        DWindowExactMassExactSpeedFiniteCanonicalLimit finiteOperatorLayer S
      let Bdata :=
        buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
          finiteOperatorLayer
          Cshared
          finiteCanonicalLimit
      let Rdata := master.h_master sectorSplit sectorBounds
      DOverlapIdentityAPI
        finiteOperatorLayer.toStagePackage
        Bdata
        F
        Rdata)
    (s : ℂ)
    (hs : s ∈ RightHalfPlane finiteOperatorLayer.toStagePackage.sigma0) :
    (buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
      finiteOperatorLayer
      S
      W
      Wapi
      F
      sectors
      sectorSplit
      sectorBounds
      master
      overlapBuilder).B.Bcan s =
      ∑' q : PrimePowerPair,
        q.weightC * S.Kshared q.center s := by
  have hshared :
      (buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
        finiteOperatorLayer
        S
        W
        Wapi
        F
        sectors
        sectorSplit
        sectorBounds
        master
        overlapBuilder).B.Bcan s =
        (DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S).Bshared s := by
    exact
      (buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
        finiteOperatorLayer
        S
        W
        Wapi
        F
        sectors
        sectorSplit
        sectorBounds
        master
        overlapBuilder).B.h_Bcan_matches_shared s hs

  simpa [DWindowExactMassExactSpeedSharedPackage,
         canonicalPrimePowerPackageFromKernelTsum]
    using hshared

/--
Current sharpest RH frontier theorem.

If the exact-mass/exact-speed D-window package is supplied, and the H-side package
is functionally compatible with the same shared canonical package, then RH
follows.
-/
theorem finalRHSpine_from_DWindowExactMassExactSpeedData
    (ZF : ZetaZeroFacts)
    (finiteOperatorLayer : DFiniteStagePackageFromOperatorLayer)
    (S : CanonicalPrimePowerDWindowExactMassExactSpeedData finiteOperatorLayer)
    (W : DCanonicalWindowData)
    (Wapi : DCanonicalWindowAPI W)
    (F : DFHLimitData finiteOperatorLayer.toStagePackage)
    (sectors : DResidualSectorData finiteOperatorLayer.toStagePackage)
    (sectorSplit :
      DResidualSectorSplitAPI finiteOperatorLayer.toStagePackage sectors)
    (sectorBounds :
      DResidualSectorBoundsAPI finiteOperatorLayer.toStagePackage sectors)
    (master :
      DMasterResidualAPI finiteOperatorLayer.toStagePackage sectors)
    (overlapBuilder :
      let Cshared := DWindowExactMassExactSpeedSharedPackage finiteOperatorLayer S
      let finiteCanonicalLimit :=
        DWindowExactMassExactSpeedFiniteCanonicalLimit finiteOperatorLayer S
      let Bdata :=
        buildDBcanLimitDataFromOperatorFiniteCanonicalLimit
          finiteOperatorLayer
          Cshared
          finiteCanonicalLimit
      let Rdata := master.h_master sectorSplit sectorBounds
      DOverlapIdentityAPI
        finiteOperatorLayer.toStagePackage
        Bdata
        F
        Rdata)
    (X : HMeromorphicWithNormalFormPoles)
    (Compat :
      AppendixESharedPackageFunctionalCompatibility
        (buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
          finiteOperatorLayer
          S
          W
          Wapi
          F
          sectors
          sectorSplit
          sectorBounds
          master
          overlapBuilder)
        X) :
    RiemannHypothesis :=
  finalRHSpine_after_sharedPackageFunctionalCompatibility
    ZF
    (buildDDetailedConstructionWithOperatorLegalityFromDWindowExactMassExactSpeed
      finiteOperatorLayer
      S
      W
      Wapi
      F
      sectors
      sectorSplit
      sectorBounds
      master
      overlapBuilder)
    X
    Compat

end

end RHFormalization
