import RHFormalization.OmegaPuncturedIdentityEndpoint
import RHFormalization.DefaultZetaZeroFacts
import RHFormalization.EtaPositivity
import RHFormalization.DesignedDetailedConstruction
import RHFormalization.HMeromorphicWithNormalFormChosenCshared
import RHFormalization.InterfaceFromCommonCshared
import RHFormalization.OmegaPuncturedIdentityFromCodiscrete
import RHFormalization.OmegaCodiscreteIdentityFromNormalForms
import RHFormalization.MainTheoremFromRealZeroFreeOmegaPunctured
import RHFormalization.MainTheoremFromRealZeroFreeOmegaCodiscrete
import RHFormalization.CurrentFrontierEndpoint

namespace RHFormalization

#check h_real_zero_free
#check defaultZetaZeroFacts_of_realZeroFree h_real_zero_free
#check designedY

#check buildHMeromorphicWithNormalFormPolesWithChosenCshared
#check buildHMeromorphicWithNormalFormPolesWithChosenCshared_Cshared_eq
#check buildInterfaceBridgeNonnegativeFromCommonCshared

#check buildOmegaPuncturedIdentityFromCodiscrete
#check buildOmegaCodiscreteIdentityFromNormalForms
#check defaultOmegaPreperfectAPI

#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity

-- Existing wrapper candidates:
#check RH_from_designed_D_zero_density
#check RH_from_eta_zeroDensity_holo

end RHFormalization
