import RHFormalization.MainTheoremFromRealZeroFreeOmegaPunctured
import RHFormalization.MainTheoremFromRealZeroFreeOmegaCodiscrete
import RHFormalization.OmegaCodiscreteIdentityFromNormalForms
import RHFormalization.OmegaNormalFormPropagationEndpoint
import RHFormalization.OmegaMeromorphicLocalPropagationEndpoint
import RHFormalization.OmegaMeromorphicZeroPropagationEndpoint
import RHFormalization.OmegaMeromorphicZeroPropagationClopen

namespace RHFormalization

#check mainTheorem_from_realZeroFree_omegaPuncturedIdentity
#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_omegaPuncturedIdentity
#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_codiscreteIdentity
#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormCodiscreteIdentity
#check mainTheorem_from_default_connectedOmega_meromorphicAlgebra_normalFormPropagation
#check finalConditionalRHSpine_meromorphicLocalPropagation
#check finalConditionalRHSpine_meromorphicZeroPropagation
#check finalRHSpine_after_zeroPropagation

#check defaultOmegaMeromorphicZeroPropagationAPI

#print axioms defaultOmegaMeromorphicZeroPropagationAPI
#print axioms finalRHSpine_after_zeroPropagation

end RHFormalization
