import RHFormalization.CurrentFrontierEndpoint
import RHFormalization.HMeromorphicWithNormalFormChosenCshared
import RHFormalization.ExplicitFormulaLocalReduction
import RHFormalization.ZpoleFromSeries
import RHFormalization.HPPEndgame
import RHFormalization.ReflectionPairPoleClass
import RHFormalization.DefaultPoleNormalFormLayer
import RHFormalization.HExplicitFormulaSplitChosenCshared
import RHFormalization.ShiftedLaplaceRegularFromZeroDensity
import RHFormalization.DesignedDetailedConstruction

namespace RHFormalization

#check defaultZeroMultiplicityData
#check defaultZeroExhaustion
#check ZpoleSeries defaultZeroMultiplicityData
#check defaultZpoleConvFromZeroDensity
#check meromorphicOn_from_convergence
#check h_pp_from_convergence
#check buildHSideGroupedPoleNormalFormDataFromPrincipalPartsPair
#check defaultPoleNormalFormLayer

#check shiftedLaplaceHarchPackageFromHolo
#check shiftedLaplaceHarchPackageFromHolo_split
#check HarchPackageFromChosenCsharedAddZpole
#check HarchPackageFromChosenCsharedAddZpole_split

#check buildHMeromorphicWithNormalFormPolesWithChosenCshared
#check finalRHSpine_after_zeroPropagation

end RHFormalization
