import RHFormalization.CanonicalPrimePowerHeatKernelNatValueMajorantSummability
import Mathlib.Topology.Algebra.InfiniteSum.Real
import Mathlib.Analysis.PSeries

#check summable_prod_of_nonneg
#print summable_prod_of_nonneg
#check summable_sigma_of_nonneg
#print summable_sigma_of_nonneg
#check Real.summable_nat_pow_inv
#check Real.summable_one_div_nat_add_rpow
