import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds
import RHFormalization.CanonicalPrimePowerConcreteCountBound
import RHFormalization.CanonicalPrimePowerCountWeightProductBound

namespace RHFormalization

#check CanonicalPrimePowerDWindowSoundCountingFactorBoundsData
#print CanonicalPrimePowerDWindowSoundCountingFactorBoundsData

#check PrimePowerCenterCountingSetData
#print PrimePowerCenterCountingSetData

#check PrimePowerSoundMassCountingSetWeightEnvelopeData
#print PrimePowerSoundMassCountingSetWeightEnvelopeData

#check countEnvelope_along_cutoff_le_concrete_countBound

end RHFormalization
