import RHFormalization.CanonicalPrimePowerSoundCountingFactorBounds
import RHFormalization.CanonicalPrimePowerConcreteCountBound
import RHFormalization.CanonicalPrimePowerWeightEnvelope
import RHFormalization.CanonicalPrimePowerCountWeightProductBound

namespace RHFormalization

#check concreteCountBound
#check concreteCountBound_nonneg
#check countEnvelope_le_concreteCountBound

#check PrimePowerWeightEnvelopeData
#print PrimePowerWeightEnvelopeData

#check countWeight_div_denominator_tendsto_zero_of_cutoff_factor_bounds
#print countWeight_div_denominator_tendsto_zero_of_cutoff_factor_bounds

end RHFormalization
