import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope

namespace RHFormalization

#check sharpCutoffConcreteChosenSpeed_speed_eq
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.massEnvelope_div_windowSpeed_tendsto_zero
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toSharpCutoffMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope
#check canonicalPrimePowerSharpCutoffChosenLengthMassEnvelope_h_Bcan_matches_tsum

#print axioms CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.massEnvelope_div_windowSpeed_tendsto_zero
#print axioms CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toSharpCutoffMassEnvelopeData
#print axioms CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.toExhaustionData
#print axioms buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope
#print axioms canonicalPrimePowerSharpCutoffChosenLengthMassEnvelope_h_Bcan_matches_tsum

end RHFormalization
