import RHFormalization.CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelope
import RHFormalization.CanonicalPrimePowerSharpCutoffMassEnvelope
import RHFormalization.CanonicalPrimePowerDWindowExactWindowSpeed

namespace RHFormalization

#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffChosenLengthMassEnvelopeData.massEnvelope_div_windowSpeed_tendsto_zero

#check CanonicalPrimePowerSharpCutoffMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffMassEnvelopeData.toMassEnvelopeData
#check CanonicalPrimePowerSharpCutoffMassEnvelopeData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerSharpCutoffMassEnvelope
#check canonicalPrimePowerSharpCutoffMassEnvelope_h_Bcan_matches_tsum

#check CanonicalPrimePowerDWindowExactWindowSpeedData
#check CanonicalPrimePowerDWindowExactWindowSpeedData.toExhaustionData
#check buildDBcanLimitDataFromCanonicalPrimePowerDWindowExactWindowSpeed
#check canonicalPrimePowerDWindowExactWindowSpeed_h_Bcan_matches_tsum

end RHFormalization
